### ISSUE TITLE
Support totalCount in search response

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#1081]
The search API now returns the total count of records matched, alongside the matched records ref. https://xata.io/docs/api-reference/db/db_branch_name/search#free-text-search

Clients can use this information to determine whether there are more results pages to fetch.

**Comment by SferaDev** [comment]
I checked and we would need to do a breaking change to support totalCount in the SDK. We were planning some breaking changes with a v1, so adding it to the list
