### ISSUE TITLE
execution environment check doesn't account for server side dom lib

### ISSUE THREAD

**Issue by advancedtw** [xataio/client-ts#1088]
**Describe the bug**

using the sdk and a server side dom library will fail to pass  [isBrowser check](https://github.com/xataio/client-ts/blob/c38ec84568aafbbf0d772e15308289ecc9529cc5/packages/client/src/client.ts#L84C14-L84C14)

**To Reproduce**

```ts 
import { Window } from "happy-dom";  // or jsdom
const window = new Window(); 
global.window = window;
```
window is no more undefined. yet we are not running in the browser

**Software version**

all version are affected.

**Comment by SferaDev** [comment]
Hey! @advancedtw unfortunately there are no great ways to detect if it's running on a browser or not. We will review to make the check a bit more robust however if you are polyfilling browser APIs it's likely it still hits a face positive.

In any case, to the client constructor you can pass the `enableBrowser: true` flag to remove the warning.

The main goal for that check is not that the SDK is not compatible with browser runtimes (it actually is) but to prevent a user from running it from an untrusted environment and leaking the API key.

**Comment by advancedtw** [comment]
I understand and I have a workaround for my situation however if we can come up with a solution for this kind of edge case that would be better.   It's not uncommon for the backend to rely on server side dom manipulation. in my case I'm using lexical in headless mode to do some data conversion. unfortunately there is a pending issue on lexica side #https://github.com/facebook/lexical/issues/3097#issuecomment-1511496254 and it's not clear when they will address it.

> In any case, to the client constructor you can pass the enableBrowser: true flag to remove the warning.

it's not a warning it actually throws but certainly better than leaking api keys.

**Comment by SferaDev** [comment]
Yeah we can check for some browser only APIs + window. I'll think about it and see if we can improve it. Thanks for reporting!
