### ISSUE TITLE
Add ``local`` and ``git`` resolvers for ``branch`` option

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#11]
The SDK resolves the branch the first time it needs it. It goes one by one, until it finds a string or a function that resolves in a stiring. Example:

```ts
import {local, git} from '@xata.io/client-utils/branch-resolution'

branch: [process.env.XATA_BRANCH, local, git, 'main']
```

In this case `local` and `git` are async function that return string, undefined or null. The resolved branch name will be stored in the XATA_BRANCH env variable. If it's not defined, it'll resolve the functions sequentially. If none of them return a defined string, the branch name used will be `main`.

**Comment by SferaDev** [comment]
Closing as we've already implemented branch resolution in a different way
