### ISSUE TITLE
[Attachments]: Meta attributes on attachment records aren't discoverable by TypeScript

### ISSUE THREAD

**Issue by snide** [xataio/client-ts#1123]
Right now the meta details on attachments need to be read manually. At the most basic, if you want the `url` of file, you need to either `read()` or `select()` it. When you try to make that call, TypeScript will complain.

Preferably, these meta fields (including `attributes`) would come along by default with the file details. I can't think of an instance where I wouldn't need that information. 

![image](https://github.com/xataio/client-ts/assets/324519/2a658ef7-2525-47d1-b8f2-d79115a5173a)

**Comment by SferaDev** [comment]
We will update the typings when the backend shows all fields as required except for base64Content and signedUrls
