### ISSUE TITLE
[Attachments]: We should provide a client-side transform helper that works client-side

### ISSUE THREAD

**Issue by snide** [xataio/client-ts#1124]
Currently you need to manage image transforms server side. This means you're often needing to be very thoughtful about the image sizes you need before it hits the client. You then also need to a decent amount of TS shape manipulation with whatever parameters you pass down.

Instead, it would be much easier to just handle image transforms on the client through a helper.

**Comment by SferaDev** [comment]
I already added this on the latest build 😉
