### ISSUE TITLE
better app navigation

### ISSUE THREAD

**Issue by y-71** [xataio/client-ts#1176]
**Is your feature request related to a problem? Please describe.**
the current state of the app is great but the UI is not easy to navigate and resize

i can't resize my window without losing control over the app, if it's full screen, i can't see the full name of my tables, if i resize the screen smaller, i can't get to change the screens and have to resize to a bigger screen again to find my tables
<img width="1512" alt="Screenshot 2023-09-15 at 18 21 54" src="https://github.com/xataio/client-ts/assets/37041878/d93f50f8-38f0-4a88-8451-f75a75786273">
<img width="737" alt="Screenshot 2023-09-15 at 18 29 04" src="https://github.com/xataio/client-ts/assets/37041878/6d5e2da0-5565-42fa-8ec8-acc37c276b1f">

**Describe the solution you'd like**

a twitch like interface, it would be amazing to have a window manager like https://github.com/nomcopter/react-mosaic to manage the ability to have multiple screens open and the ability to resize them, the issue being that since changing the components will be an issue since each component has a different place in the tree, maybe you can use portals to mitigate that issue https://legacy.reactjs.org/docs/portals.html

eventually, having more control over the screens

just having a better navigation

**Comment by alexfrancoeur** [comment]
Thank you for reporting and sharing all these details @y-71! We definitely appreciate the feedback. It sounds like there are three issues here.

1. Your longer table names aren't visible in the nav
2. There is no way to navigate across tables in a small screen / mobile view
3. Having a more flexible workspace

I'm dropping in a few folks who can help us with designing a better system for navigation to address the first two issues. @snide @richardgill @SferaDev

The third one is more of an enhancement request, but I really like the idea. If you're open for it, I'd love to learn more about how you're using Xata and other ideas you might have.

**Comment by SferaDev** [comment]
@alexfrancoeur Closing this issue since it's not related to the SDK nor CLI. Would you mind connecting via support or discord?
