### ISSUE TITLE
i can't find any `next_auth` verification token

### ISSUE THREAD

**Issue by y-71** [xataio/client-ts#1177]
**Describe the bug**

when using nextauth with the xata adapter, i can't find any next_auth verification token on the table,

I've followed the xata adapter docs for nextauth https://authjs.dev/reference/adapter/xata

**Expected behavior**
next_auth verification token

**Software version**
```
(base) ➜  ~ xata --version
@xata.io/cli/0.13.4 darwin-arm64 node-v18.14.0
```

```
"dependencies": {
    "@next-auth/xata-adapter": "^0.2.2",
    "@t3-oss/env-nextjs": "^0.3.1",
    "@xata.io/client": "^0.25.2",
    "next": "^13.4.2",
    "next-auth": "^4.22.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "zod": "^3.21.4"
  },
```

**Additional context**

<img width="737" alt="Screenshot 2023-09-15 at 18 29 04" src="https://github.com/xataio/client-ts/assets/37041878/7396105c-5ef8-45ad-be68-ba50048e6739">
<img width="1624" alt="Screenshot 2023-09-15 at 18 30 43" src="https://github.com/xataio/client-ts/assets/37041878/3b197d70-06f8-4121-9fd5-edb110a31e09">

**Comment by alexfrancoeur** [comment]
@SferaDev when you have a moment, any chance you could dig into this? It looks like our adapter may be broken.

**Comment by y-71** [comment]
@alexfrancoeur is all of your product open source? i can try to file a PR for this

**Comment by y-71** [comment]
@alexfrancoeur and @SferaDev i've opensourced a `xata-auth` sample for you to test it, 

my question is, does the `nextauth_verificationTokens` table still make sense knowing that there is a `sessionToken` field in the `nextauth_sessions` table

https://github.com/y-71/xata-auth

**Comment by SferaDev** [comment]
@y-71 Verification tokens are only for email sign-in to build magic links, if you are using google auth that table will always be empty. If you find any other problem feel free to open a new issue 😄 

> i've also found this PR by @SferaDev about adding oauth and it's still on draft, i'm using google auth solely for this project at this level, not sure if it's relevant since it looks like it's just for the cli

This is unrelated to `next-auth` and will add a new way to log in to the CLI.
