### ISSUE TITLE
`.read()` doesn't return relationship data

### ISSUE THREAD

**Issue by marlonmarcello** [xataio/client-ts#1195]
**Describe the bug**

I apologize in advance, I am not sure if this is a bug.  
But if I use `.read()` to get a record from a table that as a column type of `Linked to table` (relationship), it only returns the ID of the linked record.  
I understand it and it makes sense but a lot of the other operations return the whole data including relationship data, I was expecting `read()` to do the same.

**To Reproduce**

1. Create a `client` table
1. Create an `employee` table with a `Link to table` column to `client`
2. Add some data to both
3. Fetch a record by ID using `read()` from `employee`

```ts
import { getXataClient } from "./xata";
const xata = getXataClient();

const record = await xata.db.employee.read("rec_ck1puj7cba7m1glr09b0");
console.log(record);
```

Notice that the logged data doesn't include the `client` data.

**Expected behavior**

Using `.read()` should return relationship data like `getMany` and other operations.

**Software version**

`@xata.io/cli/0.13.12 darwin-arm64 node-v18.18.0`

**Additional context**

Once again, apologies if this is expected behaviour. And if it is, is the best recommendation just to fetch the relationship data?
Example in a NextJs app:

```tsx
import { getXataClient } from "@/xata";

const xata = getXataClient();

export default async function Employee({
  params: { id },
}: {
  params: { id: string };
}) {
  const employee = await xata.db.employee.read(id);
  const client = await xata.db.client.read(project.employee.id);

  return (
    <div>
      <pre>
        <code>{JSON.stringify(project, null, 2)}</code>
      </pre>
      <pre>
        <code>{JSON.stringify(client, null, 2)}</code>
      </pre>
    </div>
  );
}
```

**Comment by eemmiillyy** [comment]
Hi @marlonmarcello, thanks for the report! This behaviour is intended; non id fields on linked records will not be returned with `.read()` requests by default. Instead of making 2 requests, you can do something like this to return all the fields on the linked record:
```typescript
const employee = await xata.db.employee.read(id, ['client.*']);
```
If you want to target specific fields on the linked record rather than all of them (with `*`) you can do something like:
```typescript
const employee = await xata.db.employee.read(id, ['client.name']);
```
We will work on our [documentation](https://xata.io/docs/sdk/get#selecting-columns-from-the-linked-tables) to clarify this as this part can be a bit confusing. Thanks for bringing this up!

**Comment by kostasb** [comment]
Hey @marlonmarcello thank you for highlighting this! We expanded the relevant section in docs [here](https://xata.io/docs/sdk/get#selecting-columns-from-the-linked-tables) to cover fetching linked column content when getting a record by id. Let us know if you have any questions or suggestions, here or at support@xata.io!

**Comment by marlonmarcello** [comment]
⚡ So quick! That's awesome. Thanks team!
