### ISSUE TITLE
[Attachments] `signedUrl` raises type error on column selection

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#1201]
```
xata.db.foo.select(['file.signedUrl'])
```

**Comment by eemmiillyy** [comment]
Can't reproduce this issue, I think it can be closed. 
<img width="1026" alt="Screenshot 2023-11-08 at 09 34 46" src="https://github.com/xataio/client-ts/assets/55739812/0eaad7cc-de2d-468b-9b2b-32d8edea06e8">
Photo is type `file` and attachments is type `file[]`
