### ISSUE TITLE
Type error beyond 3 levels of recursion

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#1221]
**Describe the bug**

The TS SDK encounters an error beyond 3 levels of recursion for linked columns.

```
Type '"two.three.four.id"' is not assignable to type 'SelectableColumnWithObjectNotation<OneRecord, []>'. Did you mean '"two.three.four"'?(28
```

![image](https://github.com/xataio/client-ts/assets/15780449/4e08a748-66bc-4c50-b602-46aa74f09f92)

**Comment by SferaDev** [comment]
With TypeScript we cannot infer when to stop recursion. Each nested level adds a bigger amount of compute to the type checker and the LSP.

We decided to cut recursion because with some schemas that link to themselves (or to themselves in 2 levels) the IDE language services would crash itself.
