### ISSUE TITLE
[Types] Expose Transaction types

### ISSUE THREAD

**Issue by marlonmarcello** [xataio/client-ts#1223]
**Is your feature request related to a problem? Please describe.**

I am trying to create a dynamic transaction entry generator. Bear with me please.
A third party tool my company uses exports data in a JSON format.  
I am trying to go through this JSON and create an array of transaction operations.  

Something like:
```ts
function generateTransactions(jsonData) {
  const transactions = jsonData.map((entry) => {
    const table = entry.identityName;
    const record = sanitizeData(entry)

    return {
      insert: {
        table,
        record
      }
    }
  })
}
```

This example is simplified, I will have to make updates as well in case the ID already exists in the DB.  

There is another use case in the project as well where I have a debouncer on a set of form inputs that process a dynamic set of transaction operations after the timer runs out to avoid constantly updating the DB as the user types.

**Describe the solution you'd like**

I'd like to be able to have proper types for my dynamic function based on the types that Xata already has on the client package.  
Is it possible to expose the following types? 
1. `TransactionOperation`
2. `InsertTransactionOperation`
3. `UpdateTransactionOperation`
4. `DeleteTransactionOperation`

**Describe alternatives you've considered**

In some parts of the project I am pretty much duplicating those and using specific record types:
```ts
type UpdateTransactionOperation<O extends XataRecord> = {
  id: string;
  fields: Partial<EditableData<O>>;
};

type TaskUpdateTransaction = UpdateTransactionOperation<TaskRecord>;
```

And in another instance I did infer from the parameter, which isn't very nice:
```ts
import { getXataClient } from "@/xata";

import type { CreateProjectResponse, ProjectWithEmployees } from "../types";

const xata = getXataClient();

type TransactionParameter = Parameters<typeof xata.transactions.run>[0][0];
```

**Additional context**

**Comment by SferaDev** [comment]
Something like this would help, right?

https://github.com/xataio/client-ts/commit/9077d966c6136803c012c49b305bc00516d280c0

**Comment by SferaDev** [comment]
Going to tag a release now with the change (release might take a few minutes).

Please update and let me know if we can help you with anything else 😉

**Comment by marlonmarcello** [comment]
Yess! Thanks @SferaDev 🌟
