### ISSUE TITLE
`xata pull` not writing files synchronously?

### ISSUE THREAD

**Issue by richardgill** [xataio/client-ts#1239]
**Describe the bug**

I ran this command in my terminal: 

`(cd apps/website && xata pull main) && git commit -am ‘removed gitsha column’  && git push`

Then when I came back to my terminal I noticed some migration files that were 'untracked' in git. 

Does `xata pull` wait for the files to be written before returning?

**Comment by SferaDev** [comment]
I was checking the code and it looks like we wait for all write operations to succeed before returning. Looks like something to investigate for sure.

**Comment by eemmiillyy** [comment]
TIL using the `-a` flag  will only add modified files, NOT new or deleted files. In the [commit](https://github.com/xataio/frontend-next/pull/2569/files) where this was experienced, new files were being added rather than modified which explains why they weren't part of the commit.
