### ISSUE TITLE
Check for new CLI release

### ISSUE THREAD

**Issue by sepal** [xataio/client-ts#1248]
**Is your feature request related to a problem? Please describe.**

I've ran into the issue at least twice, that I didn't realize that I was running an older version of the cli and thus running into bugs, that were fixed in newer version. 
Recently for example I was still running 0.13.3 on my PC which had an issue with initializing a new db with a schema file.

**Describe the solution you'd like**

It would be awesome if the cli should check if there is a newer release and notify the user about it, just like npm or cli tools do.

**Comment by SferaDev** [comment]
We are working on it! We will update this issue once released.
