### ISSUE TITLE
Add description to schema properties in codegen

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#128]
[off-topic] Do you know how/if we can retrieve this description from the API?

I don't see it so far 😢 
![image](https://user-images.githubusercontent.com/1761469/165709705-81939dc1-ac5c-4a4a-82a8-955ac2ada2b9.png)

_Originally posted by @fabien0102 in https://github.com/xataio/frontend-next/pull/753#discussion_r860616266_

**Comment by fabien0102** [comment]
🙄 I'm not using the `client-ts` in the screenshot, I think the `description` is not exposed at the openapi level 😇 

https://github.com/xataio/openapi/blob/dacf601a1723c944cad0fd8f60f8f20cdf252ecb/bundled/openapi.yaml#L3233-L3269

**Comment by fabien0102** [comment]
https://github.com/xataio/openapi/issues/129

**Comment by SferaDev** [comment]
Still good to also track it here 😄
