### ISSUE TITLE
Set the type of parameter ids in Repository.prototype.read to ReadonlyArray

### ISSUE THREAD

**Issue by narumincho** [xataio/client-ts#1286]
When processing GraphQL queries, I use DataLoader to avoid having to access Xata for each field.

The ids type of the function passed to the DataLoader constructor is ReadonlyArray.

So I use the unnecessary spread syntax to convert ids from ReadonlyArray<T> to T[] to pass to Xata's Repository.read.

```ts
import DataLoader from "npm:dataloader";

const xataClient = new XataClient();

const teamDataLoader = new DataLoader<string, Team>(async (ids) => {
  const teams = await xataClient.db.team.read([...ids]); // Spread syntax not required?
  return teams.map((team, index) =>
    team === null ? new Error(`team id=${ids[index]} not found`) : team
  );
});
```
Please change it to receive ids as ReadonlyArray like [Deno.KV.prototype.getMany](https://deno.land/api@v1.39.0?s=Deno.Kv&unstable=&p=prototype.getMany).

https://github.com/xataio/client-ts/blob/8f1444ac9cfd283ee767d8222163b2d4263c2080/packages/client/src/schema/repository.ts#L168

```ts
abstract read(ids: ReadonlyArray<Identifier>): Promise<Array<Readonly<SelectedPick<Record, ['*']>> | null>>;
```

**Comment by SferaDev** [comment]
Hey @narumincho!

Would a union work with DataLoader?

Something like `read(ids: Identifier[] | ReadOnlyArray<Identifier>)`?

**Comment by narumincho** [comment]
```ts
read(ids: Identifier[] | ReadonlyArray<Identifier>) // A
read(ids: ReadonlyArray<Identifier>) // B
```
A does not solve this problem, B solves this problem.

**Comment by narumincho** [comment]
```ts
const idsNotReadonly: string[] = ['0', '1'];
const idsReadonly: ReadonlyArray<string> = ['0', '1'];

function readOld(ids: string[]) {}
function readA(ids: string[] | ReadonlyArray<string>) {}
function readB(ids: ReadonlyArray<string>) {}

readOld(idsNotReadonly); // ok
readOld(idsReadonly); // type error

readA(idsNotReadonly); // ok
readA(idsReadonly); // ok

readB(idsNotReadonly); // ok
readB(idsReadonly); // ok
```

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlgEwgORFASgUwIYPAGwE8AuGaAJzjAHMBtAXRgF4ZaByABjYBoY2BGNvQDcAKFCRYiCFlwESMWXjBEAguXLZCAHgpVqAPmatOPPoJGjRAMwCuYYFDjgY5HAgDy+BAApppPRoGAEoYAG8AXxt7R2cwV3dVPyQAqEogxgAfRXd5dU0dQMNQyOiHJxc3XAAhZIhSJTyNLV00-QMSqNEqz2861AxclUJgsR6vX2lG4dGYAHo5mChCAAdMGEwNEHIrHqTpAemiUe7EuqORsVOa-rQLk57aqaHjsSA

**Comment by SferaDev** [comment]
I was afraid that some invocations failed, but literals, tuples and others seem to work

**Comment by SferaDev** [comment]
It will be released per schedule next monday by @eemmiillyy
