### ISSUE TITLE
Trasaction get operation type error

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#1308]
Version: `@xata.io/client@0.28.3`

Transaction `get` operation raises a type error:

```ts
const result = await xata.transactions.run([
  { get: { table: "prices", id: "rec_cm83un8m922cq6bl2i30", columns: ["id", "original_price"] } },
]);
```

> Object literal may only specify known properties, and 'get' does not exist in type 'NarrowRaw<TransactionOperation<DatabaseSchema, keyof DatabaseSchema>>'.(2353)

![image](https://github.com/xataio/client-ts/assets/15780449/0da68e57-699a-40a5-b5d6-8a0ab7428abb)

Reported on [Discord](https://discord.com/channels/996791218879086662/1192725745420734526/1192725745420734526).

**Comment by SferaDev** [comment]
Duplicated of https://github.com/xataio/client-ts/issues/964

We never really implemented it 🥲

**Comment by kostasb** [comment]
Thank you. Closing this one but it would be good add https://github.com/xataio/client-ts/issues/964 to our priotiries otherwise we should remove it from the docs https://xata.io/docs/sdk/transaction#gets.
