### ISSUE TITLE
Incorrect handling of `NULL` values in query results using Drizzle and Xata

### ISSUE THREAD

**Issue by realmikesolo** [xataio/client-ts#1314]
**Describe the bug**

The problem occurs when performing a select query on a table that contains columns with NULL values using `@xata.io/drizzle`. When I use other drivers with drizzle, for example, `pg` everything works out.

**To Reproduce**

```typescript
export const userTable = pgTable('users', {
  id: varchar('id', { length: 255 }).primaryKey(),
  name: text('name'),
  gender: text('gender'),
});
```

```typescript
const result = await db.select().from(usersTable);
```

```typescript
// result
[
  { id: 'rec_cmbi5ajff3lbs66vplug', name: '', gender: '' },
  { id: 'rec_cmbi8frff3lbs66vpms0', name: '', gender: '' }
]
```

Results in an output where `NULL` values are incorrectly replaced with empty strings.

**Expected behavior**

The expected behavior is that the query should return `NULL` values.

```typescript
// result
[
  { id: 'rec_cmbi5ajff3lbs66vplug', name: null, gender: null },
  { id: 'rec_cmbi8frff3lbs66vpms0', name: null, gender: null }
]
```

**Software version**

@xata.io/client: "^0.28.3",
@xata.io/drizzle: "^0.0.14"

**Comment by SferaDev** [comment]
Hey @realmikesolo, we have merged a fix for this issue in the backend. We are currently rewriting the drizzle adapter to support both http and wire protocol connections. I will leave the issue open until we release the new one and double check it works there too. Thanks for reporting!

**Comment by realmikesolo** [comment]
Hey, @SferaDev! Thanks for your work
