### ISSUE TITLE
Importer package improvements

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#142]
Context https://github.com/xataio/client-ts/pull/127#pullrequestreview-962246080

- [ ] Add delimiter option (semicolons, tabs, spaces)
- [ ] Review different encodings (latin1)
- [ ] Add a non-interactive flag, make all commands to inquiry instead of erroring out, if flags are provided ignore the inquiry question (related to https://github.com/xataio/client-ts/pull/127/files#r864487665)
- [ ] Add a way to call interactively as an npm package (API)

**Comment by richardgill** [comment]
@SferaDev is this still open? If so, I've assigned it a P2, please just change it if that's not right.
