### ISSUE TITLE
How to make group by request??

### ISSUE THREAD

**Issue by irg1008** [xataio/client-ts#1421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kostasb** [comment]
The closest equivalent of `group by` in the Xata API is [summarize](https://xata.io/docs/sdk/summarize).

If no aggregation function is specified in it, summarize returns results as a "distinct" - equivalent to `SELECT name FROM "users" GROUP BY name;`

In case you need to execute a grouping statement that is not supported by the summarize API, you can instead run SQL. The SQL-over-HTTP API is available in the TypeScript SDK: https://xata.io/docs/sdk/sql/overview#examples

Also, Beta access was just launched for wire protocol Postgres (SQL) connectivity: https://xata.io/blog/serverless-postgres-platform which enables using ORMs ([Prisma](https://xata.io/blog/prisma-postgres-xata-integration), [Drizzle](https://xata.io/blog/drizzle-postgres-xata-integration)).

We try to keep the scope of issues in this repo around SDK bugs and enhancement requests. Please consider using [discord](https://xata.io/discord) or [contact support](https://support.xata.io/hc/en-us/requests/new) for questions!

**Comment by irg1008** [comment]
I see thats very helpful. I love the sdk, of course is missing things like nested inserts (inserting link). And it gives some issues when using cloudflare. (node:buffer not found)

Great work and the platform is very promising. Best of luck
