### ISSUE TITLE
How can we configure Delete behaviours like cascade

### ISSUE THREAD

**Issue by irg1008** [xataio/client-ts#1423]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kostasb** [comment]
The Beta Postgres-enabled databases provide a list of `On delete` options for link records, including Cascade.

![image](https://github.com/xataio/client-ts/assets/15780449/aa313c70-b4b3-40d9-9db3-4f4021cc37f1)

You can find more details about entering the Beta and creating a Postgres-enabled database in the following articles:
https://xata.io/blog/serverless-postgres-platform
https://xata.io/docs/postgres

With the "current" production databases (not Beta postgres-enabled) there is no built-in cascade functionality. When deleting a linked record, the link value becomes null in any records linking to it. Deletions of linked columns would need to be implemented in the app with filter & delete logic. Prior to deleting a record, you can take note of record ids linking to it with the reverse relation arrow (`<-`) https://xata.io/docs/concepts/data-model#links-and-relationships and perform delete operations on them.

We try to keep the scope of issues in this repo around SDK bugs and enhancement requests. Please consider using [discord](https://xata.io/discord) or [contact support](https://support.xata.io/hc/en-us/requests/new) for questions!
