### ISSUE TITLE
Consider generating types (maybe in a d.ts file) for JavaScript

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#143]
We generate `@property` annotations. See https://github.com/xataio/client-ts/blob/main/codegen/example/xata.js#L4-L12

I'm wondering if we could/should generate a .d.ts file and importing the types instead. Like [here](https://github.com/xataio/client-ts/blob/main/codegen/example/xata.js#L1)

**Comment by SferaDev** [comment]
It should be possible, you just need to create your own compiler host. I'll give it a spin 😄
