### ISSUE TITLE
Failed to run Edge Function

### ISSUE THREAD

**Issue by PaulieScanlon** [xataio/client-ts#1437]
**Describe the bug**
Hi all, not sure if this is a Xata thing, or a Netlify thing but, i'm trying to use Xata with Netlify Edge Functions.

E.g 

```typescript
import { XataClient } from '../../src/xata';

const xata = new XataClient({
  apiKey: Netlify.env.get('XATA_API_KEY'),
  branch: Netlify.env.get('XATA_BRANCH'),
});

export default async function handler() {
  try {
    const { records } = await xata.sql`SELECT * FROM users`;

    return new Response(JSON.stringify({ message: 'A-Ok!', data: records }, null, 2), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  } catch (error) {
    return new Response({
      status: 500,
      headers: { 'content-type': 'application/json' },
    });
  }
}

export const config = { path: '/get-all-users' };

```

But i'm seeing the following error. 

```
◈ Failed to run Edge Function get-all-users:
TypeError: Module not found "file:///Users/paulscanlon/Documents/Paulie/work/Netlify/development/serverless-postgres-for-js-devs/netlify-xata-astro-test/src/xata".
    at file:///Users/paulscanlon/Documents/Paulie/work/Netlify/development/serverless-postgres-for-js-devs/netlify-xata-astro-test/netlify/edge-functions/get-all-users.ts:1:28
    at async file:///Users/paulscanlon/Documents/Paulie/work/Netlify/development/serverless-postgres-for-js-devs/netlify-xata-astro-test/.netlify/edge-functions-serve/dev.js:7:35 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

**To Reproduce**

1. Clone the repo: [https://github.com/PaulieScanlon/netlify-xata-astro-test](https://github.com/PaulieScanlon/netlify-xata-astro-test)
2. Install deps `npm install`
3. Install Netlify CLI (globally) `npm i netlify-cli -g`
4. Run `netlify dev`

**Expected behavior**

On the `/edge-function` page the response should be visible in the HTML `<pre>` element. 

**Software version**
I'm using the following Xata versions.

```
    "@xata.io/cli": "^0.0.0-next.vb0a85c9143c13dd5082810db994a5fede59bb0a4",
    "@xata.io/client": "^0.0.0-next.vb0a85c9143c13dd5082810db994a5fede59bb0a4",
```

**Additional context**

I'm writing a guide for [Netlify Developers](https://developers.netlify.com/) and would like to demonstrate all the ways Xata can be used, notably.

- Xata SDK (SSR)
- SQL over HTTP (SSR)
- Ideally from within Edge Functions (CSR)
- "Ordinary" Postgres `pg`

I've added pages to this Astro site to show the different approaches. If you spot anything that's incorrect, please lemme know and i'l fix it up. 

Ta!

**Comment by PaulieScanlon** [comment]
My bad, it was my mistake. Here's how i solved it [edge-functions/api/#import-maps](https://docs.netlify.com/edge-functions/api/#import-maps)

At the root of my project i created a `deno.json`. E.g

```json
{
  "imports": {
    "xata": "./src/xata.ts"
  }
}
```
Then add the import_map path to `netlify.toml`. E.g


```toml
[functions]
  deno_import_map = "deno.json"
``` 

The i changed the import in my edge function. E.g

```diff
+ import { XataClient } from 'xata';
- import { XataClient } from '../../src/xata';

const xata = new XataClient({
  apiKey: Netlify.env.get('XATA_API_KEY'),
  branch: Netlify.env.get('XATA_BRANCH'),
});

export default async function handler() {
  try {
    const { records } = await xata.sql`SELECT * FROM users`;

    return new Response(JSON.stringify({ message: 'A-Ok!', data: records }, null, 2), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  } catch (error) {
    return new Response({
      status: 500,
      headers: { 'content-type': 'application/json' },
    });
  }
}

export const config = { path: '/get-all-users' };
```

Works like a charm!

**Comment by PaulieScanlon** [comment]
Hi @SferaDev, to be fair. There's a fair amount of "extra stuff" that you gotta do for Netlify Edge Functions. 

There's the changes i mentioned above which are required, but you'll also see  `Netlify.env.get('XATA_API_KEY')` rather than `import.meta.env.XATA_API_KEY` (Vite) or `process.env.XATA_API_KEY` (Node)

Also, in my repo i've since added a Netlify Function (standard Lambda) example: [sf-get-all-users.ts](https://github.com/PaulieScanlon/netlify-xata-astro-test/blob/main/netlify/functions/sf-get-all-users.ts)

In Lambda environments you can use the normal import, the import maps are for Edge environments, and i assume something specific to Deno E.g

```typescript
import { XataClient } from '../../src/xata';
```

**Comment by SferaDev** [comment]
No problem, @PaulieScanlon what do you think of https://github.com/xataio/mdx-docs/pull/324?

**Comment by PaulieScanlon** [comment]
Hey @SferaDev, this great man. Thanks for the update.

I wonder if it's also worth showing the following.

1. A full example of a Netlify Edge Function

2. An example of a regular Netlify Serverless Function with a not about the difference in import

3. A mention that the Netlify CLO must be installed "globally"

4. A mention that netlify dev is the command to run

Here's my test repo which has a number of examples.

https://github.com/PaulieScanlon/netlify-xata-astro-test

**Comment by kostasb** [comment]
That's a great suggestion @PaulieScanlon , Xata docs currently doesn't provide guidance for running Xata in edge functions. We are taking note and will follow up.

**Comment by PaulieScanlon** [comment]
Cool man! Thanks @kostasb. Top work team! Some good stuff going on here!

**Comment by rishi-raj-jain** [comment]
A great team work. Let me know if I can help with a starter repository.
