### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#152]
A couple of things that I found while dog-fooding:

- Errors returned by `withStatus` don't have a stack trace. I had an error and it was hard to know where it was coming from, because the backend error was very generic.
- The bulk API sometimes returns errors without a message: e.g. `{ status: 409 },` so we finally get an `Unknown error`. We should ignore those and get the error messages from the rest of operations.

**Comment by SferaDev** [comment]
Merged: https://github.com/xataio/xata/pull/710
