### ISSUE TITLE
Add CI to the repository

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#16]
- Use GitHub Actions to run tests in every push.
- Add secrets to run these tests against xata.io/sh.
- Prevent merging a PR if tests are not passing.

**Comment by SferaDev** [comment]
Two topics I'd like to raise here:

#### Compiling each package

Right now the ``client-ts`` handles two npm packages (the client itself and the codegen). I could either manually target each package (maybe even with separate actions that check the changed files path to avoid compiling both packages if only one was touched) or add something more complex to handle a workspace (ie: turborepo, nx, ~lerna~, ...).

#### Publishing canary builds

I think something that adds value is having the PRs published on ``npm`` as canary builds (only if they're from a team member or a team member approves the deployment).

Also if we decide that we won't bump the versions every time a commit to main happens (and instead schedule releases with a set of features), when pushing to main a new beta could be published (that can be tested and used meanwhile the next release happens). This discussion is related to #17

**Comment by gimenete** [comment]
I don't have experience with turborepo, nx, lerna, etc. If it's easy to use something like that for CI and publishing, great. If it's gonna take some time, I'd prefer to first implement just CI: GitHub Actions, running tests on every push. I think we should test both packages always, because if we've changed something in the codegen we could've broken the compatibility with the client and viceversa.

I like the idea of canary builds. Like I said, depending on how complex it is, I'd choose impelmenting only CI for now, or everything at the same time.
