### ISSUE TITLE
Implement a release strategy

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#17]
So far I've been doing `npm publish` manually, but we should automate that.

**Comment by fabien0102** [comment]
https://github.com/google-github-actions/release-please-action

For ref, this is what I'm usually using for this kind of problem

**Comment by SferaDev** [comment]
@fabien0102 I very much enjoyed how the GitHub ``primer`` team does it.

In every PR you create a changeset file (markdown with frontmatter) where you set the description of the change for the release notes and the type to know how to bump the version number (ie: patch, minor, major). A bot helps you to create that file.

When the PRs are merged a bot is keeping track of them and opening another PR for ``Release Tracking``. In the moment you merge it, the changeset files are removed, the version is bumped following semver according to the changes included, the changelog file is updated, the version is pushed to ``npm`` and the release is tagged on GitHub.

What do you think of that approach?

Example: https://github.com/primer/react/pull/1894

**Comment by TejasQ** [comment]
Given that #19 is merged and we have automatic canary publishes _and_ a manual workflow, is this closeable? Or is there more to be done here?

**Comment by gimenete** [comment]
I think we can close it.

@SferaDev WDYT?

**Comment by SferaDev** [comment]
I would like to have a more concise release strategy when actual users begin using the library.

For example, a bot that keeps track of the changes and decides which semver bump is needed and prepares the release notes.

Maybe we can keep this open as a low priority task but that needs to be implemented before public beta?

**Comment by gimenete** [comment]
Sounds good 👍

**Comment by gimenete** [comment]
I've never used semantic commits such as feat, chore, etc. but I can learn. No strong opinions.

Agreed that having the ability to PATCH a record is a main blocker. I think that was close to be done in the backend, right? And agreed that also links (and objects!) is the other high priority.

> Before that point we would need to begin documenting breaking changes and making sure we follow semver.

👍
