### ISSUE TITLE
Let's separate the codegen from the client installation steps

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#2]
I feel this will help users get started much faster without mixing too many concepts. We can add codegen as a "cherry on the cake" after.

**Comment by gimenete** [comment]
Code generation is a mandatory step. In fact the generated code is what you'll import later:

```
import { XataClient } from './xata';
```

`XataClient` is part of the generated code.

**Comment by TejasQ** [comment]
Got it. I'll cover this in the docs. 😄
