### ISSUE TITLE
Make the codegen CLI a bit typesafe

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#22]
Ref: https://github.com/xataio/client-ts/pull/20#issuecomment-1058295307

**Comment by SferaDev** [comment]
I've used https://github.com/Schniz/cmd-ts in the past, worth taking a look at? @fabien0102 @TejasQ

**Comment by TejasQ** [comment]
That looks great, but probably the least friction with what we have already–even by the same author–is https://github.com/Schniz/soundtype-commander. As I understand, it's a drop-in replacement for Commander but with "excellent type inference". 😬

**Comment by TejasQ** [comment]
Hmmmm okay, I was wrong. It's not a drop-in replacement.

**Comment by TejasQ** [comment]
Let's try https://github.com/Schniz/cmd-ts 🔥

**Comment by SferaDev** [comment]
Closing since we're moving to oclif which is typesafe.
