### ISSUE TITLE
Codegen depends on `src` directory

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#225]
Repro: https://xata.rewatch.com/video/ukvo8ck54tgq9hlw-vercel-integration-dx-journey?t=535

Two problems:

1. It inactionably fails if there's no `src` directory
2. When passing another `-o mypath/thing.ts` output folder, it fails if `mypath` doesn't exist. I would prefer if it creates the directory, since it is a _code generator_ and it creates files anyway

Proposed solution:

Put client in `pwd`, allow `-o` to customize for subdirectories

**Comment by gimenete** [comment]
I'll look into it, but it is supposed to create any required directory:

https://github.com/xataio/client-ts/blob/219c3d144ad788d74c3863d36e30aed300810a63/packages/codegen/src/generateWithOutput.ts#L15

**Comment by gimenete** [comment]
I cannot reproduce this problem.

https://user-images.githubusercontent.com/50486/170239969-6944d336-77ca-46f0-9b21-edb8e1ba9e04.mp4

Can you check what version of the codegen are you using?
