### ISSUE TITLE
Make codegen from branch configurable

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#226]
Repro: https://xata.rewatch.com/video/ukvo8ck54tgq9hlw-vercel-integration-dx-journey?t=585

Right now, I can only generate code from my database's `main` branch. What if I don't have a `main` branch and my default branch is `sparkles`? What if I want to generate code from a `dev` branch? Let's add a `--branch [name]` flag and prompt with an interactive selector if the branch cannot be found.

I think inferring the branch from the git repo is dangerous because it's not expected, and we ought to give users a bit more control with this flag.

**Comment by gimenete** [comment]
> Right now, I can only generate code from my database's main branch

That's not really what it does. The codegen tries to find a xata branch with the same name as the git branch.

I watched the video, and this is precisely why we need "focus-mode" in the vscode extension. You are editing a branch in vscode that is not "checked out" by git. So any command line (the cli, codegen, etc.) won't know what branch you are using.

> I think inferring the branch from the git repo is dangerous because it's not expected

We agreed on that here https://www.notion.so/Branching-workflows-with-no-xata-dir-a3493cc457a345d5b1979fd7d94e726b

Associating git branches with xata branches is necessary for many reasons:
- Typically you will do database changes and code changes at the same time. So xata and git branches need to be associated.
- CI needs to know what branch to use. Git is the best way to infer that.
- Same for preview/staging environments.

**Comment by gimenete** [comment]
For additional info, this is the algorithm: https://github.com/xataio/client-ts/blob/main/packages/client/src/util/config.ts#L23-L36

Right now we assume `main` is the default branch, but this will change as soon as we have that concept in the backend.

**Comment by TejasQ** [comment]
Sorry, I must have missed that discussion in Notion.

Do we expect that every UI branch will have a database branch in this case? What if:

- a button is red, should be blue
- UI dev does `git checkout -b fix-color`
- Decides she wants the latest DB schema, runs codegen
- DB doesn't have `fix-color` branch, and probably shouldn't because the branch is about a _color_

What would happen in this scenario?

**Comment by gimenete** [comment]
When you create a git branch but not a corresponding xata branch (because you don't need schema changes), if we had environments, your code will point to `main` but to your personal environment (not production).

Since we don't have time to do that, we are going to implement a "fallback branch" option. Typically you'd create a personal branch, that is the default branch for your local development.

See _Option 1c_ here https://www.notion.so/Discussion-Branches-and-Environments-776fc6f281d042ea82923f58206c2a55#367ab5fe46ac4931bd35451b016d047c

**Comment by TejasQ** [comment]
Okay, well today I learned a lot from this Notion doc I missed.

Will close this. Thanks for the info!
