### ISSUE TITLE
Shell does not have type-safety

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#229]
Sorry if this is a known issue, please feel free to close if it is.

Repro:

https://user-images.githubusercontent.com/9947422/169699254-4a427b9a-95ff-4162-a0b4-665ed52ca4f7.mov

**Comment by SferaDev** [comment]
Yeah, REPL is not type safe in any case (not TypeScript safe). Although the proxy hides the namespaces.

We briefly discussed this with @gimenete last Thursday. And to improve the DX we can either tweak a little bit the Proxy target or play with the suggestions in the REPL.

Good to have the issue tracking though
