### ISSUE TITLE
Make `databaseURL` optional and inject it using the information in `xata/config.json` during code generation

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#25]
Now that we have a `xata/config.json` file (we didn't have it a few months ago), we can read the workspace id and the database name during code generation and inject it in the code.

Users should still be able to overwrite its value for a few reasons:
- So the URL is configured with mechanisms like env variables. Useful for example if for security reasons somebody wants to run a codebase in a different workspace/database, or because it's a forked open source project and they don't want to change the generated code every time just to change the workspace/database, etc.
- For us, to test our generated code against localhost or staging.

**Comment by SferaDev** [comment]
If we add default strategies to guess and set the branch, we can do the same approach for databaseURL

**Comment by gimenete** [comment]
> If we add default strategies to guess and set the branch, we can do the same approach for databaseURL

Yeah, I was thinking on something like that. However I think the workspace and database almost never changes. So I prefer the default to be injected in the code, and we can do that during code generation.

In the (not common) case you want to overwrite that value, you still can.

For deciding the branch name I can think of many different strategies (git, untracked file, env variable), but for workspace/database I can't think of other useful strategies other than allowing it to overwrite it completely.

> Similarly we can attempt to read the apiKey from ~/.config/xata/key.

That's interesting. However this needs to be done in runtime (unlike workspace/database), and there we need to deal with different file system APIs for different environments.

**Comment by SferaDev** [comment]
> However I think the workspace and database almost never changes. So I prefer the default to be injected in the code, and we can do that during code generation.

Makes sense, what about we do have strategies but the codegen injects it (overwriting). That way we consistently make all the SDK parameters optional but still the codegen prints values to the code.

**Comment by gimenete** [comment]
> what about we do have strategies but the codegen injects it (overwriting)

The thing is that I can only think about one strategy: using an env variable. And that's a sync operation. So I don't see the need to allow an async function or array of async functions, etc. I'm open to adding strategies definitely if we find other use cases.

To me branches are a very particular case, becuase you may want to configure that very dynamically depending on the environment (local, ci, preview, production,...) and I can see many different strategies there.

**Comment by TejasQ** [comment]
This is blocking my example apps. Any objection if I take it?

**Comment by gimenete** [comment]
@TejasQ no objections. Go for it! 👍 

The change in `XataClientOptions` would be:

```diff
  export type XataClientOptions = {
    fetch?: unknown;
-   databaseURL: string;
+   databaseURL?: string;
    branch: BranchStrategyOption;
    apiKey: string;
    repositoryFactory?: RepositoryFactory;
  };
```

and the codegen would inject a default `databaseURL` value inferred from `xata/config.json`.

**Comment by TejasQ** [comment]
Right, should we also infer the branch the same way as `main` and have it be a reasonable default since all databases are created with `main`?

**Comment by TejasQ** [comment]
To avoid conflicts, it would be awesome if we can merge

#38 so that the `generate` function works with the folder already, and
#34 so I can be more confident I don't break other codegen parts

before I start on this 🙌

**Comment by gimenete** [comment]
> Right, should we also infer the branch the same way as main and have it be a reasonable default since all databases are created with main?

For branches we have strategies. And even though all databases start with a `main` branch, that doesn't mean that that's the default branch or could be renamed. Besides, it could be problematic that you deploy to an environment that is misconfigured and by mistake starts using the production branch. So I prefer to not have any default.

**Comment by TejasQ** [comment]
Great, sounds good.

**Comment by TejasQ** [comment]
My only concern with making `branch` explicitly required when instantiating this class is _friction_. Everyone we talk to on customer calls doesn't even know about branches and using them is usually something that comes later, after they start iterating on a `main` schema. 

So to ask a user to supply `branch: "main"` even when they're not fully using Xata in a big way seems like unnecessary friction because my assumption is that they would start using the SDK _before_ getting overly familiar with the branching flow.

**Comment by gimenete** [comment]
> Everyone we talk to on customer calls doesn't even know about branches

I'd like to learn more about that. Are they familiar with git branches?

**Comment by gimenete** [comment]
Well, it's a relief they know about git branches. I thought you were saying they didn't know about branches in general.

Anyway, this is a security measure. I think we can't have default because it may cause a lot of harm in some circumstances. Maybe in the future, depending how we do API keys scoped to branches or environments we can add a default safely.
