### ISSUE TITLE
Rename page options to paging

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#262]
During Alberto's demo on workers I noticed he thought the page meant something different. We should review those names

**Comment by SferaDev** [comment]
Not sure which is better naming. WDYT @gimenete? New ideas (I don't really like these either) 

```diff
export type QueryOptions<T extends XataRecord> = {
-  page?: PaginationOptions;
+  paging?: PaginationOptions;
  columns?: NonEmptyArray<SelectableColumn<T>>;
  filter?: FilterExpression;
-  sort?: SortFilter<T> | SortFilter<T>[];
+  sorting?: SortFilter<T> | SortFilter<T>[];
  cache?: number;
};
```

**Comment by gimenete** [comment]
I think I'd keep `sort` and I'd change `page` to `pagination`. WDYT?
