### ISSUE TITLE
Tests are a bit flaky on CI

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#28]
They [sometimes fail](https://github.com/xataio/client-ts/runs/5552760203?check_suite_focus=true), sometimes don't after a retry. 🧐

**Comment by SferaDev** [comment]
Yeah, ``integration`` tests fail if two actions run at the same time (they interact with the same table).

We could create/delete tables on demand but we would need schemaless operations in the SDK: Related to https://github.com/xataio/frontend-next/discussions/586#discussioncomment-2364140

**Comment by gimenete** [comment]
For now I think we can prevent this in the workflow: https://github.com/xataio/client-ts/pull/37

Long-term solutions is having environments!
