### ISSUE TITLE
Feedback on the general CLI workflows

### ISSUE THREAD

**Issue by tsg** [xataio/client-ts#308]
First of all, I love playing with the CLI! Sorry for the bullet-points format below, I'm making individual tickets about particular functionality (shell, edit mode, etc), but this one collects more general feedback.

* `-h` doesn't do what I was expecting (`--help` works)

* I love the `xata browse` command :)

On `xata init`:

* I think the question on `Select where to store your configuration` is unnecessary. Should we standardise on `.xatarc` and only allow `package.json` via a CLI flag?

* IMO we don't need to send the user in the `schema edit` mode (I'll post separate ticket about that), especially when you start from an existing DB. I'd prefer if `xata init` stops and then says something like:

> Run `xata browse` to edit the schema via UI, or `xata schema edit` to edit the schema in the shell.

* When I try the `--schema=` option, I get:

```
╰─$ xata init --schema=/tmp/schema.json                                                    1 ↵
✔ Select a workspace › Demo
✔ Select a database or create a new one › test
✔ Do you want to install the TypeScript/JavaScript SDK? … no
✔ Select where to store your configuration › .xatarc
    Error: A databaseURL was not defined. Either set the XATA_DATABASE_URL env variable or
    pass the argument explicitely
```

But I did select a DB, so it seems like a bug?

* When running with `--force`, I no longer get the workspace/db selection question. Does it use the one in `.xatarc`? I was expecting `xata init --force` to mean "re-init" or "start fresh".

On `xata dbs`:

* `xata dbs list` asks me to select a workspace, but it could maybe work with the workspace from `.xatarc`?

On `xata branches`:

* `xata branches list` doesn't seem to work outside of a git repo, but it feels like it should

* I was surprised that `xata branch create` seemed to automatically create a git branch and even push it to the remote? This feels a bit invasive to me, perhaps it's better for the user to run the git commands themselves?

* The preview in `xata merge addFeature` seems to have problems with the deleted column names:

```
$ xata merge addFeature                                                                  1 ↵
Date Jun 15, 2022, 7:34 PM

Table users:
 DELETE column  0

? Do you want to apply the above migration into the main branch? › (Y/n)
```

**Comment by gimenete** [comment]
Thanks for the feedback!! The bullet points format work great for me 😄 

I've addressed most of the feedback in this PR https://github.com/xataio/client-ts/pull/311

I haven't been able to reproduce the `Error: A databaseURL was not defined. Either set the XATA_DATABASE_URL env variable or pass the argument explicitely` error though. Will keep investigating.
