### ISSUE TITLE
Watch mode for codegen

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#326]
Just adding this so we don't lose track of it

please ignore for now

**Comment by SferaDev** [comment]
Watch mode for codegen, right?

**Comment by TejasQ** [comment]
Yes sir

**Comment by SferaDev** [comment]
PR for testing, every second request. We will need websocket support for a better approach, for now if you need it for demos you have it around. I'll let @gimenete decide if we merge as-is or not.
