### ISSUE TITLE
Add integration test for all supported TS versions

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#332]

**Comment by SferaDev** [comment]
Seems we don't support 4.4 or earlier. I would've thought the most recent feature we used was tempalte literal types introduced in 4.1

**Comment by SferaDev** [comment]
I've been investigating, we have limit with 4.5 (I added compat for new ``cause`` in Error). We cannot go below, because ``Awaited`` was introduced and is needed for type inference.

**Comment by richardgill** [comment]
@SferaDev has this actually been done already?
