### ISSUE TITLE
CLI auth success page needs design

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#348]
After creating an API key, we show this to a user:

<img width="1892" alt="image" src="https://user-images.githubusercontent.com/9947422/175812964-fec4a281-10b3-4f02-a316-8f74dc4adb1d.png">

Let's make this look better.

cc @DavidCnoops for ideas

**Comment by AlenaNik** [comment]
@TejasQ to keep the Empty / Error / Success pages consistent across app UI and SDK we are keeping it aligned to the top, and centered horizontally at the moment. The reason: on taller screen it might look a bit weird and 'disconnected' from the rest of the UI. On smaller screens (e.g. laptop size) we could align it to the center. However, we didn't make the decision yet and for SDK we can iterate a bit more 👍  cc @DavidCnoops
