### ISSUE TITLE
CLI auth error visual refinement

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#349]
Currently the error attached to the input looks unrefined:

<img width="1892" alt="image" src="https://user-images.githubusercontent.com/9947422/175813040-4b214abd-f433-41d8-9635-06cbe4adb87d.png">

To adjust, I suggest adding some space between the error box and the input field, but @DavidCnoops has the final say before devrel review/approval.

**Comment by gimenete** [comment]
![image](https://user-images.githubusercontent.com/50486/180433117-bf1e9123-2796-4372-af94-964e3beaea57.png)

![image](https://user-images.githubusercontent.com/50486/180433151-a7eb8962-211c-4ef5-97eb-153325866081.png)

This is how it looks right now. Thoughts @AlenaNik ?

**Comment by TejasQ** [comment]
Should we maybe add a red border to the input and bring the error a bit closer?
