### ISSUE TITLE
No shorthand flags

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#351]
The Xata CLI works great with long-form flags (like `--force`), but does not have equivalent short-form flags (`-f`). Let's fix this to improve the developer experience.

**Comment by gimenete** [comment]
We do have some shorthands. Example:

https://github.com/xataio/client-ts/blob/4f36065a2dba5473143c61aa5792863fc4a3caa4/cli/src/commands/schema/dump.ts#L14

and 

https://github.com/xataio/client-ts/blob/4f36065a2dba5473143c61aa5792863fc4a3caa4/cli/src/commands/codegen/index.ts#L23-L26

I'll add some more, but most of the times I just prefer not having a shorthand if it's not clear enough.

**Comment by TejasQ** [comment]
Yeah, from what I've spoken to developers they have mixed feelings about shorthands, but the often used ones are convenient (like `-d` for databaseUrl) or similar. Happy to trust your judgment here based on what _should_ and _shouldn't_ have shorthand versions and iterate as needed.

I apologies for not doing the legwork of listing _specific_ shorthand properties that would have helped our developer experience with the CLI. I'll be a bit more thorough next time.
