### ISSUE TITLE
Updated CLI directory structure

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#352]
## Status Quo

- `./cli` contains the CLI–a package published to npm, but it isn't in `./packages` like the other packages. 
- `./cli/src/commands/[command]/` with no subcommands contains a single file and maybe a test. ([Example](https://github.com/xataio/client-ts/tree/606999fe954ad83f196ddf12248364cf22e084f9/cli/src/commands/shell))
- `./cli/src/commands/[command]/[...subcommands]` contains a flat structure with multiple **subcommands**, each with a test. ([Example](https://github.com/xataio/client-ts/tree/606999fe954ad83f196ddf12248364cf22e084f9/cli/src/commands/auth))

Concretely, this is the current directory structure:

```
client-ts
│   cli
|   └───src
│   |   └───commands
│   │   |   └───simple-command
│   │   │   |   |   index.ts
│   │   |   └───command-with-subcommands
│   │   │   |   |   create.ts
│   │   │   |   |   create.test.ts
│   │   │   |   |   delete.ts
│   │   │   |   |   delete.test.ts
│   │   │   |   |   update.ts
│   │   │   |   |   update.test.ts
```

## Proposal

I propose turning each subcommand into a directory, enabling each directory to contain documentation and smaller modules that each command may require along with tests. Concretely, we're proposing the following augmentation to the directory structure:

```
client-ts
│   cli
|   └───src
│   |   └───commands
│   │   |   └───simple-command
│   │   │   |   |   README.md
│   │   │   |   |   index.ts
│   │   |   └───command-with-subcommands
│   │   │   |   └───create
│   │   │   |   |   |   README.md
│   │   │   |   |   |   create.ts
│   │   │   |   |   |   create.test.ts
│   │   │   |   └───delete
│   │   │   |   |   |   README.md
│   │   │   |   |   |   delete.ts
│   │   │   |   |   |   delete.test.ts
│   │   │   |   └───update
│   │   │   |   |   |   README.md
│   │   │   |   |   |   update.ts
│   │   │   |   |   |   update.test.ts
```

## Okay, but why?

Off the bat, we're not a fan of deeply nested directories since they can be hard to navigate. In this case however, they will allow us to properly document each command, and use this documentation to build the [global documentation site](https://docs.xata.io). It will also allow breaking commands down into smaller modules isolated to their scope to potentially help maintainability.

Expressed as a pros and cons table, this is what we see:

|✅ Pros|❌ Cons|
|---|---|
|We can bundle documentation per command, which makes the public GitHub repo more accessible and can help build the docs site.|The project becomes less accessible by becoming potentially harder to navigate.|
|We allow breaking down larger code blocks from certain subcommands into smaller modules that can help maintainability and testability.||

## Alternative Consideration: JSDoc

Since the bulk of the intent of this proposal is to increase accessibility and developer experience quality through documentation, we could instead lean more towards adding JSDoc-style documentation [above each command](https://github.com/xataio/client-ts/blob/606999fe954ad83f196ddf12248364cf22e084f9/cli/src/commands/auth/login.ts#L4-L5) which we then parse and use to build the docs. 

The trade-offs here are:

|✅ Pros|❌ Cons|
|---|---|
|We get hints _directly in VS Code_ when working with the CLI codebase, but this is a CLI and not an importable library so this may not be such a big benefit.|Each command does not have a README and is therefore not as accessible when browsing this public repo in GitHub|
|The directory structure stays lesser-nested and potentially easier to navigate and more accessible on GitHub.|More complexity in parsing comments for documentation generation.|

Looking forward to the thoughts and comments on this. 🎉

**Comment by gimenete** [comment]
The layout is provided [by oclif](https://oclif.io/docs/topics#docsNav).

Having `commands/create/create.ts` will create a `xata create create` command. So this is something we don't want to do.

I think the general idea is that commands are self-explanatory with the things that oflif provices us such as a description, examples, flag descriptions, etc. People won't need to go to the code to read jsdocs to understand how commands are supposed to work.

Regarding markdown docs, I think the CLI should be self-explanatory and in a different place we should have a guide, which doesn't necessarely explains each command one by one, but provides a general view of the CLI and different workflows.

**Comment by SferaDev** [comment]
Also if it's needed to read `description`, `flags`, `examples` to generate docs for the commands, those are `static` fields in the class that can be easily read.

**Comment by TejasQ** [comment]
Thanks. Generally, it's a DX no-no to assume things are self-explanatory. I'll look into using the easily readable fields instead.
