### ISSUE TITLE
`xata random-data` succeeds without tables in a database

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#353]
## Status Quo

When running `xata random-data`, it exits with a zero exit code in a database with no tables.

https://user-images.githubusercontent.com/9947422/175816043-c6ac03ac-b128-4dfa-9ebf-5fff4edf42a6.mov

## Expected

When a database has no tables, we error with:

```
Your database has no tables. To create one, use `xata schema edit`. Once your database has at least one table, running this command again will generate random data for you. 
```

**Comment by gimenete** [comment]
I think it's ok not to error. I'll add a summary message to indicate how many tables have been affected.

**Comment by TejasQ** [comment]
Sorry, #359 did not fix this. I was about to review, but it was merged in 9 minutes and apparently the behavior wasn't reviewed to fit this issue?

Here's what happens:
![2022-06-27 10 46 47](https://user-images.githubusercontent.com/9947422/175898991-82c505e6-ed7e-411b-b587-04e7a43e3635.gif)

Per this issue, the expected behavior is that we error and let the user know they have no tables. See "Expected" heading in the issue.

**Comment by SferaDev** [comment]
I agree with @gimenete that we shouldn't error in this particular case, and the new log message states if there were records added or not.

The command ``random-data`` did not fail, it just had no records to create.

To me before failing I normally think what would I expect if it ran in a CI environment. If I had the random-data command in a GH Action to populate tables, would I expect it to fail?

**Comment by TejasQ** [comment]
The expectation from a developer's perspective when running this command is that it _inserts_ data. This is also reflected in the description:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/9947422/175901585-04ed60b1-27cc-4b8f-9e5e-79c36c4cfc23.png">

If something is expected to insert data but it doesn't, this is considered unexpected behavior. Another word for unexpected behavior is an exception/error state.

About the CI point, I do think CI should fail if you try to insert data but there are no tables. But generally outside CI, I believe it's more about either meeting or failing to meet expectations. When a developer runs this command against a new database which _may or may not have tables_ in it, the expectation is it inserts data. If it can't, we need to guide the developer appropriately.

As a compromise, what if we instead changed the output and didn't error?  Something along the lines of `We tried to insert random data, but you have no tables. To create one, use \`xata schema edit\`. Once your database has at least one table, running this command again will generate random data for you.` instead of the current `Inserted 0 records across 0 tables`? The former is a bit more explicit and actionable, where the latter can cause initial confusion for developers. I can already see a few users scratch their heads thinking "why 0 records?" before reading to the end of the sentence.

> Also, if having no tables is an error for random-data, sending --records 0 should also be an error?

I'd say yes, because the user's doing something nonsensical. TypeScript errors if we try to do things like 

```ts
if (true === false) {

}
```

so our developer experience can be similar.

**Comment by SferaDev** [comment]
What about something like this: https://github.com/xataio/client-ts/pull/360

P.S. Sorry just saw your comment

**Comment by gimenete** [comment]
I guess we can close this now since https://github.com/xataio/client-ts/pull/360 is merged
