### ISSUE TITLE
`id` doesn't exist on type, but it does

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#386]
## Repro

On build: 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/9947422/177000589-81711e0a-bbc5-47d2-bb31-12bf33afc8f1.png">

At runtime: 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9947422/177000616-f0f858a7-e699-47ca-8c2b-7696f5578579.png">

## Expected

Types are accurate, and `id` is expected.

**Comment by gimenete** [comment]
Can you share the query? I guess you are doing a `select()` and not including the `id`, right?

**Comment by SferaDev** [comment]
The query and the schema would be helpful. You can pass it via Slack if you prefer to to show it publicly.

**Comment by TejasQ** [comment]
Oops, sorry I’ve been a bit delayed with providing more context here. My bad! Will prioritize this as soon as I can!

**Comment by TejasQ** [comment]
Figured out the issue. My app is using `Item` instead of `ItemRecord` or `Item & XataRecord`. Closing. 🙂
