### ISSUE TITLE
xata init fails - "invalid column type [datetime]"

### ISSUE THREAD

**Issue by selbekk** [xataio/client-ts#390]
I've set up a few tables in my database. When I run the `xata init` command (just installed the CLI), I get the following output:

```
❯ xata init
You only have a workspace, using it by default: xxx
? Do you want to pull from an existing database? public
Pulling database schema...
invalid column type [datetime]
```

I did indeed have a date field in one of my tables. Removing that column fixed the issue. But I would love to have date fields 😅

**Comment by SferaDev** [comment]
Hi @selbekk, thanks for your bug report. Could you please tell us the version of the CLI you have installed?

I just tried with 0.3.0 and it has initialized the project with a date column.

**Comment by selbekk** [comment]
❯ xata -v
Xata CLI version 0.0.30

**Comment by selbekk** [comment]
I installed the CLI with the instructions here: https://docs.xata.io/cli/getting-started#

Is this not the correct way?

**Comment by SferaDev** [comment]
Right, you have installed the old CLI. We're in the middle of rewriting the docs for that part, apologies.

You can install the new CLI with: `npm install -g @xata.io/cli`

**Comment by selbekk** [comment]
Oh. Thanks, that worked much better 😅

**Comment by SferaDev** [comment]
Since you're using the date columns, I will publish now the next release we had scheduled for the SDK that fixes one bug in the client for date columns!
