### ISSUE TITLE
`url` intent isn't clear

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#4]
Is the `url` when instantiating the client intended to be a base URL? Or a specific URL for databases? Can one do workspaces operations with it? I'm not sure I understand this:

![image](https://user-images.githubusercontent.com/9947422/152831046-374b9c77-847a-4194-b1f8-a40f0f6cc715.png)

It suggests one instance of a client per DB Branch?

**Comment by gimenete** [comment]
This SDK is meant to be used to manage the data of a specific branch, in a specific database, in a specific workspace.

Maybe in the future we'll provide a different SDK to manage workspaces, databases and branches. But it's not the case for this SDK.

So the URL is the base url for a specific branch, in a specific database, in a specific workspace.

**Comment by TejasQ** [comment]
Thank you! Continuing the discussion here: https://github.com/xataio/client-ts/issues/3#issuecomment-1031725974
