### ISSUE TITLE
Shall we environmentalize the Xata URL? 

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#401]
## Current Status
Currently, the Xata production environment is hardcoded and the CLI can only talk to production for authentication. 

https://github.com/xataio/client-ts/blob/f8b83c6284d194b1d88bd8a2de0626f2b45a8f83/cli/src/auth-server.ts#L57

## Proposal

Shall we make this an environment variable so we can work against a local environment or staging or others?

**Comment by SferaDev** [comment]
We're working to improve this with the profiles feature!

**Comment by gimenete** [comment]
There's been some work but it's not finished.

The `~/.config/xata/credentials` file is an `ini` file. You can do `XATA_PROFILE=foo xata ...` and it will pick up the configuration for that profile. Example:

```
[default]
apiKey=xau_xxx

[staging]
api=staging
web=http://localhost:3000
apiKey=xau_xyz
```

With `XATA_PROFILE=staging` you can use staging for most commands, while running the frontend in localhost.

It's not finished and it's not documented. But that's the idea.

**Comment by gimenete** [comment]
Closing because we support profiles now.
