### ISSUE TITLE
Work with arbitrary TypeScript version

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#403]
So, I usually use `typescript@next` in all my projects because, worst case, CI fails and changes never go public while I also use the latest/next typescript version. The CLI refuses to work with this by not installing the client because of version conflicts.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/9947422/178145743-5682575b-36f5-4f91-bc43-71b8d30041f2.png">

Can we allow developers to work with anything above a minimum version of TypeScript? I kind of expect issues by using `@next` anyway. We could maybe warn but let the installation proceed or something. I usually get around this when `npm install`-ing by using `--force`, but since the CLI runs this command, I can't even `--force`. Another idea would be to add `--force` to the `init` command that ignores these peer dependencies? Sorry, just spitballing. Would love to see how we can solve this best.

**Comment by SferaDev** [comment]
We support 4.8, not sure why nom fails as we have a 4.5+ requirement without top limit.

**Comment by TejasQ** [comment]
My guess is because prerelease versions (`v0.0.0-xxxxx`) are not comparable with non-prerelease versions, so the comparison fails.

**Comment by SferaDev** [comment]
Not really, this is not a 0.0.0 prelease either, just different channel but semver tagged nightly. Must be the final .date, weird that npm doesn't handle that...

In any case doesn't fail to install to me, just warns out.

**Comment by TejasQ** [comment]
If it helps,

```
➜ node -v
v16.15.1
➜  npm -v
8.11.0
```

**Comment by SferaDev** [comment]
We added min version and E2E for all supported versions. Closing
