### ISSUE TITLE
Let's make migrations atomic

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#405]
From the `xata schema edit` command, each step in a migration is executed (create table, create columns, etc.), but if one fails, the state of the resulting migration is _partially_ completed. This leaves a database in a mixed/indeterminate state. We think it might be safer and more valuable that a migration is only committed when all operations succeed, kind of like transactions in relational databases.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/9947422/178145959-bc75c471-231a-431a-9ed1-041ea18dd74e.png">

After running a migration where one column's creation failed, I was left with a malformed schema. I expect other developers would land in similar states. 😅

**Comment by gimenete** [comment]
Yeah, we need this. We'll use the migrations API, but it's not ready yet.
