### ISSUE TITLE
Include SDK version, operation to API calls

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#414]
Suggestion:

- `x-xata-sdk-version`, `x-xata-sdk-operation`
- User Agent

**Comment by tsg** [comment]
SGTM.

**Comment by richardgill** [comment]
Thanks for this @SferaDev!

Could you give me a couple of examples of the sorts of values we might pass?

How would this work for our second SDK e.g. python? How would it work for non-SDK clients e.g. CLI, (and maybe the frontend?)

**Comment by SferaDev** [comment]
What about `User-Agent`: `Xata/0.13.0 (TypeScript; getMany)` without any headers to be implemented?

**Comment by SferaDev** [comment]
I've kept it simple, added `Xata client-ts/0.13.0` for now. Operation should probably need a custom header, but I don't have the information in the fetcher so it's more complicated.

![image](https://user-images.githubusercontent.com/2181866/178427560-db002c73-e025-4676-a530-869ad1bdd9e8.png)
