### ISSUE TITLE
Random Data UI output refinements

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#451]
When inserting random data in 1 table, this is the output:

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/9947422/179244903-94e93b84-2fe5-43c7-a593-f62b8e38346b.png">

## Suggestions

1. Let's highlight the table name with backticks and a different color
2. Let's omit the last line if just 1 table, since the total number of records is the same as the first line. This will also remove the `1 tables` error, and only show for 2 or more **tables**.

**Comment by gimenete** [comment]
We did refinements regarding this.
