### ISSUE TITLE
In a project where `git` has not been initialised error shown in console

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#466]
**Describe the bug**

https://github.com/xataio/client-ts/blob/main/packages/client/src/util/environment.ts#L35

We need to redirect error output so it's not visible to the user.

**To Reproduce**

- Computer has git
- Project is not checked out under git
- Execute the XataClient in node

**Expected behavior**

Even if it tries to get the git branch, errors should be hidden to the user

**Software version**

Latest version in `next` channel.

**Comment by gimenete** [comment]
This was fixed with https://github.com/xataio/client-ts/issues/493
