### ISSUE TITLE
[Client] Can we allow `columns` in `.getOne` and `.getAll`  and co. alongside `filter` and `sort`?

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#49]
I was just using the client and was a little confused because there was no `columns` option here:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/9947422/158771816-eb46a809-66a9-41ac-925f-a4cfaa0e8874.png">

I expected the same options as visible in the UI:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/9947422/158771871-a81b70d2-8619-4ef5-9746-623ba894c9a0.png">

After looking into it a bit more, I learned that this is the API we have:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/9947422/158771986-8312b1a4-1125-455f-b528-9c40eb8a461c.png">

I find this non-idiomatic because the `select` semantic is nowhere to be found anywhere else in our products and thus feels like a new concept to learn, where the flow that would feel more natural would be

<img width="518" alt="image" src="https://user-images.githubusercontent.com/9947422/158772196-af96e097-abf7-4f01-8ae5-cd119efe946a.png">

What drawbacks do we have from this approach?

**Comment by gimenete** [comment]
We can rename `select` to `columns`. I don't like `columns` because it's not a verb, but it'd be more consistent with our API and UI.

All options that are available in the query builder will be available inside getOne and getMany.

**Comment by SferaDev** [comment]
First of all, @TejasQ Keep in mind that ``column`` selection is still not implemented.

@gimenete I believe he's meaning to remove the ``select`` method and make it an option inside the ``get`` operations. To me it also feels more idiomatic than having a ``query.select``.

**Comment by gimenete** [comment]
The `select` is useful because it works with the type system. If you `select` two columns, you get a type with only the selected columns. We are not using those columns selected to the backend yet, but we are returning a specifc type in that function, and from that point, all additional filters/sorts you do are typed based on that. So, I wouldn't remove that.

**Comment by TejasQ** [comment]
Exactly, 100% what @SferaDev said from a developer experience point of view. I think the type benefits of `.select` make sense, but I feel the cost of developer experience is too high for this benefit because `select` isn't a common verb in other Xata materials and is a new pattern exclusively to this SDK.

Given our users tend to start with the awesome web UI and "Get code snippet" flow, I can already foresee (and have experienced myself) cases where I'd naturally do `client.db.myDb.getOne({ columns: ['col1'] })` because of this. To unlearn and adjust this natural pattern causes friction, which I believe hurts the overall developer experience.

**Comment by gimenete** [comment]
> is a new pattern exclusively to this SDK.

That should be fine, because avery SDK needs to be a combination of Xata concepts and concepts of the language it's written for.

> client.db.myDb.getOne({ columns: ['col1'] })

You'll be able to do that, like I said:

> All options that are available in the query builder will be available inside getOne and getMany.

**Comment by SferaDev** [comment]
> The `select` is useful because it works with the type system. If you `select` two columns, you get a type with only the selected columns. 

We could still select the columns on the return type of all operations without a specific ``select`` operation. In fact, the ``get`` operations that return ``T`` should return a ``Select<T, SelectedColumns>``.

**Comment by SferaDev** [comment]
@TejasQ It's now your chance to provide feedback on the SDK methods and options for selecting and sorting in https://github.com/xataio/client-ts/pull/57.

Tomorrow I'll be cleaning the code/types and removing some unwanted methods and properties from the Repository that we're exposing.

**Comment by SferaDev** [comment]
Closing, already implemented 🚀
