### ISSUE TITLE
"fatal" error logged to console, but execution continues

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#493]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9947422/180815047-5eb92e91-bb05-43d9-8bd4-faa1bf08693a.png)

![image](https://user-images.githubusercontent.com/9947422/180815615-a8ab6ef5-e400-4aca-9c98-7b7e6598dc0b.png)

**To Reproduce**
Run `xata init`, `xata schema dump`, or any command in a directory that isn't a `git` repo.

**Expected behavior**
Either a warning is displayed: 

> You're not in a git repo, so Xata branches will not be mapped to git branches. More in the docs: <link>

Or, this "fatal" error is not rendered since it doesn't seem to cause any blocking problems.

**Software version**
`@xata.io/cli/0.7.0 darwin-arm64 node-v16.15.1`

**Comment by SferaDev** [comment]
Duplicated of https://github.com/xataio/client-ts/issues/466

**Comment by gimenete** [comment]
Closing in favor of https://github.com/xataio/client-ts/issues/466
