### ISSUE TITLE
[Client] Should we break up a bit the source code of the client?

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#50]
The client is a [667 line file](https://github.com/xataio/client-ts/blob/62e04e1094381b9140e12d6493a1f945cc885bce/client/src/index.ts) with a lot going on. Shall we abstract out and import the functions from this file to make iteration etc. a bit more approachable? 

Thankfully it's unit tested so we won't break much with such a change. Let me know and I'm happy to do this. 🚀

**Comment by gimenete** [comment]
Let's discuss how we want to organize it first. Like we agreed on Slack. I'll schedule a meeting.

**Comment by TejasQ** [comment]
Sure, for what it's worth, I think #46 is a wonderful starting point. 🙌  Looking forward to the discussion.

**Comment by gimenete** [comment]
I'm going to consider this done here:
https://github.com/xataio/client-ts/pull/62
