### ISSUE TITLE
[CLI] Shall we remove the code generator example?

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#504]
**Is your feature request related to a problem? Please describe.**
So every time I run `xata init`, I really don't read the example of the generated code and my brain just treats it as noise. In [this demo](https://www.loom.com/share/1b1415afaa9a45479db0e5e37ef812bf?t=570), it also doesn't have a prominent place as the "natural flow".

Moreover, its ANSI colors are hard to get right depending on the shell of the developer. It seems to add less value than we think, while increasing complexity with accessibility and maintainability.

Shall we remove it and then add it back later if users ask for it?

**Describe the solution you'd like**
A more concise "Would you like to use the code generator for type-safety?" question with less noise.

**Describe alternatives you've considered**
Leaving it the way it is.

**Comment by gimenete** [comment]
> I really don't read the example of the generated code and my brain just treats it as noise. 

Could be that you have run `xata init` multiple times, but I find it very valuable for new users. It helps them answering the question and understanding what's going on. They may even copy the code for later use.

> Moreover, its ANSI colors are hard to get right depending on the shell of the developer

I have a PR to remove the highlighting https://github.com/xataio/client-ts/pull/508
