### ISSUE TITLE
Xata commands should report where the key is retrieved from

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#505]
**Description**:
In the following scenario, xata init fails immediately after a successful xata auth login:

```
user@workstation dir % xata auth login
✔ Authentication is already configured, do you want to overwrite it? … yes
✔ Do you want to use an existing API key or create a new API key? › Existing API key
✔ Introduce your API key: … *************************************
Checking access to the API...
All set! you can now start using xata

user@workstation dir % xata init
🦋 Initializing project... We will ask you some questions.

    Error: Invalid API key
```

The reason for the error is that the env variable XATA_API_KEY was set by a script that was executed prior to the above commands. It is difficult for the user to tell the source of the issue, especially if they aren't aware of the env variable existing already. 

> Environment variable XATA_API_KEY is set, this overrides credentials set by xata auth login

It's probably a rare case but quite confusing when it occurs.

**Comment by gimenete** [comment]
Hey @kostasb 

We just shipped this https://github.com/xataio/client-ts/pull/502 It was merged yesterday and it was released this morning.

So, I think this issue should be fixed with the latest version. So I'm closing this. Give it a try and if you have further suggestions, let us know!
