### ISSUE TITLE
Codegen language selection is not working properly

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#51]
From the README:

```
xata-codegen generate [path to xata directory] -o generated/client.ts
```

If you do that in `main`, the result is a `generated/client.ts.ts` file. Note the duplicated extension

If you do

```
xata-codegen generate [path to xata directory] -o generated/client.js
```

The result is a `generated/client.js.ts` extension.

Previously the language was deducted from the extension. But now there's an optional --lang parameter that if it's not used, the extension the `.ts` extension is always added regardless of the extension the user provides. I haven't checked what happens if you use the param and also put an extension in the `-o` option.

My suggestion is to remove the --lang option and deduct the language from the extension.

cc @TejasQ 

It's easy to reproduce the probem by runnning `npm run build-example`

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/50486/158776486-819f449c-36e8-4025-82f3-88a5162643e7.png">

**Comment by TejasQ** [comment]
Oh, okay. I thought language was intended to be configurable via parameter instead of inferred from the output param since it's its own parameter here:

https://github.com/xataio/client-ts/blob/d2d0c2d1f93f029672acf9e0534a84220aa99bb8/codegen/src/codegen.ts#L95

PR incoming...

**Comment by gimenete** [comment]
The language was calculated from the output file and the output file was not modified

https://github.com/xataio/client-ts/blob/d2d0c2d1f93f029672acf9e0534a84220aa99bb8/codegen/src/index.ts#L22-L23
