### ISSUE TITLE
[SDK][Doc] Add an example with linked records

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#518]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/1761469/182780331-c76e83e9-2b75-4940-a684-660b7e2651e3.png)

**Describe the solution you'd like**
I would love 2 small examples in the documention, one with `id` and one with the entire record.

**Additional context**
The types and API were good enough for discovering the feature, well done 😁 

![image](https://user-images.githubusercontent.com/1761469/182780856-dd63ca11-463a-4a3e-9f86-c38ad8d81de4.png)

**Comment by gimenete** [comment]
Anybody in the @xataio/devrel team want to be assigned to this one?

**Comment by gimenete** [comment]
@fabien0102 any update on this?

**Comment by fabien0102** [comment]
Still on my todo, I didn't have time to check on this yet

**Comment by kostasb** [comment]
This remains a popular ask among users, maybe we can prioritize adding docs for creating and updating records with links

**Comment by SferaDev** [comment]
Done
