### ISSUE TITLE
[SDK] Exposing the `branch`

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#519]
**Is your feature request related to a problem? Please describe.**
For introspection reason, I would love to have access to the `branch` that `XataClient` use under the hood.

**Describe the solution you'd like**
```ts
const xata = new XataClient();

console.log(xata.branch); // "main"
```

**Describe alternatives you've considered**
I tried to use the `getCurrentBranchName()` method, but since the `databaseURL` is injected as `defaultOptions` in `XataClient` I couldn't use it out-of-box.

**Comment by SferaDev** [comment]
Instead of the proposed:

```ts
xata.branch; // string | undefined
```

Offering:

```ts
const { branch, databaseURL } = await xata.getConfig();
```

Does that work?
