### ISSUE TITLE
Trying to ensure that users in the same team use the same codegen version

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#527]
Some ideas:

- [x] Print codegen version in generated file.
- [ ] Ability to have a codegen version in the `engines` field in `package.json`
- [ ] Optionally having codegen as a dependency in the `package.json`
- [ ] Supporting multiple versions of the codegen at the same time. The CLI would select the proper one. Maybe using oclif plugins?

cc @xataio/devrel

**Comment by SferaDev** [comment]
Duplicated
