### ISSUE TITLE
The CLI doesn't work on windows

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#557]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1761469/184615442-a1c4cb78-c5ad-445b-bddb-0d92995a8a6a.png)

The cli is not working on windows (bash console)

**To Reproduce**
Steps to reproduce the behavior.

- Install the latest version of the cli (0.9.0 for me)
- Try to run any command

**Expected behavior**

**Software version**

`0.9.0`

**Additional context**
Probably related to this PR -> https://github.com/xataio/client-ts/pull/500
This was working on `0.8.0`

**Comment by gimenete** [comment]
Fixed here https://github.com/xataio/client-ts/pull/588
