### ISSUE TITLE
Add methods that throw

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#559]
**Describe the bug**
With the following code (simple expressjs app)
```ts
// Delete climber
  app.delete("/climbers/:id", async (req, res) => {
    const id = req.params.id;

    try {
      console.log("try");
      await xata.db.climbers.delete(id);
      console.log("success", id);

      res.status(204).send();
    } catch {
      res.status(400).json({
        message: "Can't delete this record",
      });
    }
  });
```

I was expecting a `400` status if I send `"yolo"` as `id` but instead I have a `204` and this in my console:

![image](https://user-images.githubusercontent.com/1761469/184653126-23ee4f77-c797-4c15-8a39-817a3bd57a14.png)

**Expected behavior**
I was expecting to throw an exception since the `id` is not valid.

**Software version**

`"@xata.io/client": "0.16.1"`

**Comment by SferaDev** [comment]
We don't throw on any error, when there's a situation not possible we return null. We have discussed in the past adding `actionOrThrow` methods: https://xata-hq.slack.com/archives/C032EKCBUGM/p1657121418430689?thread_ts=1657121418.430689&cid=C032EKCBUGM

Will keep this issue to implement those.

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/185080029-7227ecd4-4738-4af0-866f-e528c6529f6a.png)

I'm sorry, but from the documentation, this should already throws, nop? 🤔
