### ISSUE TITLE
Client SDK not working with Cloudflare Worker

### ISSUE THREAD

**Issue by ncheikh** [xataio/client-ts#59]
This line is not working for the following Cloudflare Worker config:

https://github.com/xataio/client-ts/blob/7fe10d6b3d936f9129408267e6cc6b9d4ea7551c/client/src/index.ts#L407

I was able to work around this by changing `this.fetch` to `fetch` at the above line.  I attempted:

1. To manipulate the constructor in RestRepository to assign cloudflare workers fetch - Did not work
2. Printing and comparing `fetch` and `this.fetch` and they report as the same.
3. Adjusting tsconfig to ES6 instead of esnext to align with client and validate this wasn't the issue - Did not work

I am really not sure why this isn't working, the only thing I added beyond the template was itty-router and faunadb (replacing with xata).  This was a problem with both local `wrangler dev` and deployed code.

Cloudflare Worker:
 - Template: https://github.com/cloudflare/worker-typescript-template

nvmrc
```
lts/gallium
```
 
tsconfig:
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "module": "commonjs",
    "target": "esnext",
    "lib": ["esnext"],
    "alwaysStrict": true,
    "strict": true,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "esModuleInterop": true,
    "types": [
      "@cloudflare/workers-types",
      "@types/jest",
      "@types/service-worker-mock"
    ]
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist", "test"]
}
```

package.json
```
{
  "name": "tasker-backend-cf",
  "version": "0.1.0",
  "main": "dist/worker.js",
  "scripts": {
    "build": "webpack",
    "format": "prettier --write  '*.{json,js}' 'src/**/*.{js,ts}' 'test/**/*.{js,ts}'",
    "lint": "eslint --max-warnings=0 src && prettier --check '*.{json,js}' 'src/**/*.{js,ts}' 'test/**/*.{js,ts}'",
    "test": "jest --config jestconfig.json --verbose",
    "xata-codegen": "xata pull && xata-codegen generate -o src/generated/XataClient"
  },
  "author": "Nabil Cheikh",
  "eslintConfig": {
    "root": true,
    "extends": [
      "typescript",
      "prettier"
    ]
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^3.0.0",
    "@types/jest": "^26.0.23",
    "@types/service-worker-mock": "^2.0.1",
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "@xata.io/codegen": "^0.2.2",
    "eslint": "^7.21.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-config-typescript": "^3.0.0",
    "jest": "^27.0.1",
    "prettier": "^2.3.0",
    "service-worker-mock": "^2.0.5",
    "ts-jest": "^27.0.1",
    "ts-loader": "^9.2.2",
    "typescript": "^4.3.2",
    "webpack": "^5.38.1",
    "webpack-cli": "^4.7.0"
  },
  "dependencies": {
    "@xata.io/client": "^0.2.2",
    "faunadb": "^4.5.2",
    "itty-router": "^2.4.10",
    "nanoid": "^3.3.1",
    "worktop": "^0.7.3"
  }
}
```

**Comment by SferaDev** [comment]
Hi @ncheikh 👋🏻

Thank you very much for your feedback! The client SDK is still in a very early stage so it's normal some things are still not fully working.

Cloudflare Workers are indeed one of our top priority deployment targets but unfortunately we had no time to test them yet. I will take a look and hopefully have it sorted out in our next release.

In any case we will keep this ticket up to date with our progress.

Thanks again 😉
