### ISSUE TITLE
Request more than 200 records, but not all records

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#609]
**Is your feature request related to a problem? Please describe.**

Using `getMany` or `getPaginated`, a user can request up to 200 records. Any more returns this error:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/9947422/188371904-23ae29e2-b8ed-4b41-9f5e-8d0272b09a56.png">

Using `getAll`, a user requests _all_ (potentially millions) of records. As far as I can see, there is no way to request 500 records using the SDK, or some limit that is not "all" and over 200.

**Describe the solution you'd like**

I'd love `.getMany({ pagination: { size: 300 } })` to work as expected: return 300 records. Same for `.getPaginated`. 

**Describe alternatives you've considered**

`.getAll({ limit: 300 })`

**Additional context**

I need this for a demo I'm doing tomorrow.

**Comment by SferaDev** [comment]
Feature added to getMany, getPaginated will match the behavior from the API
