### ISSUE TITLE
Consider generating TypeScript and then transpiling it to JavaScript when generating JS code

### ISSUE THREAD

**Issue by gimenete** [xataio/client-ts#64]
Right now the codegenerator can generate JavaScript, but maybe it's a better option to generate TypeScript and then transpile it. That could even be better to ensure that tools such as vscode find the types correctly.

My only concern is how well the generated code looks, because the generated code is something people may look at. Anyway maybe we can use prettier after the transpilation?

cc @fabien0102

**Comment by SferaDev** [comment]
Done in https://github.com/xataio/client-ts/pull/88 😄
