### ISSUE TITLE
`xata init` should log you in automatically

### ISSUE THREAD

**Issue by richardgill** [xataio/client-ts#678]
`xata init` (and any other commands that need auth?) should automatically try and log you in if you need to be logged in.

<img width="679" alt="Screenshot 2022-10-11 at 15 19 31" src="https://user-images.githubusercontent.com/6640874/195116759-3a71c925-2c57-477a-a745-ad38d5714293.png">

**Comment by gimenete** [comment]
I'm not sure about this. Erroring is not necessarely bad and with those suggestions the user learns how to use the CLI.

From https://clig.dev/

> Beyond the most utterly simple commands, running a program usually involves more than one invocation. Usually, this is because it’s hard to get it right the first time: the user types a command, gets an error, changes the command, gets a different error, and so on, until it works. This mode of learning through repeated failure is like a conversation the user is having with the program.
