### ISSUE TITLE
Problem generating an API key?

### ISSUE THREAD

**Issue by richardgill** [xataio/client-ts#681]
@amvieites had a problem generating an API key. 

Here's a problem (seems to be just him) @gimenete 

<img width="1213" alt="Screenshot 2022-10-11 at 15 23 26" src="https://user-images.githubusercontent.com/6640874/195117797-bf40055d-5915-49a4-906b-579761f4f5ca.png">

**Comment by gimenete** [comment]
It's really weird that the URL doesn't have a port. We take the port like this

```ts
const { port } = server.address() as AddressInfo;
const openURL = generateURL(port, publicKey);
```

🤔

**Comment by amvieites** [comment]
Ah, I think I deleted the screen recording already. Anyway, keep in mind that I had other issues regarding my previous environment configuration so maybe this is related and only people with previous versions of the config files/cli would experience this.
