### ISSUE TITLE
Display instructions of how to exit `xata shell` at all times

### ISSUE THREAD

**Issue by richardgill** [xataio/client-ts#682]
You can exit with ctrl+c or ctrl+d or .exit.

**Comment by SferaDev** [comment]
The `shell` is a REPL and is expected to be used by users familiar with REPLs. We follow the same behaviour as node official REPL and not showing how to exit is normal. So, I don't think we need them at all times as it will be noisy for normal experimented users. I agree though that we could show it at the beginning, as other REPLs do.
