### ISSUE TITLE
Property 'db' does not exist on type 'XataClient'.

### ISSUE THREAD

**Issue by TejasQ** [xataio/client-ts#686]
**Describe the bug**

With a local project setup with `xata init`, I experience this error when copy/pasting code from the SDK playground into my project:

|Context|Screenshot|
|---|---|
|SDK Playground|<img width="1912" alt="image" src="https://user-images.githubusercontent.com/9947422/195549440-c1d0ced5-3824-4446-b9d5-5af37ff4df13.png">|
|CLI|<img width="1261" alt="image" src="https://user-images.githubusercontent.com/9947422/195548979-360bacbc-06b1-424a-8204-ac103925afea.png">|
|App Code|<img width="1549" alt="image" src="https://user-images.githubusercontent.com/9947422/195549036-ce2d56c2-8d88-4bf7-b146-2e86eedee68f.png">|
|`xata.ts`|<img width="1136" alt="image" src="https://user-images.githubusercontent.com/9947422/195813131-556c419b-88ab-4c4d-b061-8c0de7cd4fc2.png">|

**To Reproduce**

1. Create a new TypeScript project
2. Connect it to Xata via CLI
3. Copy/paste SDK playground code into project code and run it

**Expected behavior**

I expect that the code that works in the SDK playground, also works in a local project when given the right API key.

**Software version**

- @xata.io/cli/0.9.5 darwin-arm64 node-v16.15.1
- "@xata.io/client": "^0.18.6"

**Comment by SferaDev** [comment]
The error in the SDK Playground happens due to it not having the client yet downloaded, we have improved speed a little bit but can take a few seconds and you to write something for it to pick up the types.

Regarding the local project, do you see any errors in `xata.ts` file?

**Comment by TejasQ** [comment]
None other than the one in the screenshot above: `db` in `xata.db.*` has a red underline and the error is as reported in the CLI screenshot.

**Comment by SferaDev** [comment]
Yeah, the `db` redline is normally because the library is not in the `node_modules` and the types are not computed. That's why I was asking if in the `xata.ts` it was complaining for missing types in the import.

**Comment by SferaDev** [comment]
Not able to reproduce
