### ISSUE TITLE
Error adding unique column from the CLI

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#746]
**Describe the bug**

Create unique column complains of defaultValue

**Comment by kostasb** [comment]
To reproduce:

`xata schema edit`

Add a column with uniqueness enabled, no nullable preference or default value:

![image](https://user-images.githubusercontent.com/15780449/199802847-4d607099-45d5-45b2-bedb-090b2d52383c.png)

```
Adding column testtable.name
    Error: column cannot have default value and be unique at the same time
```

Response from API endpoint `/db/<dbname>:<branch>/tables/<tablename>/columns` HTTP 400 
with message `column cannot have default value and be unique at the same time`

Reported on [discord](https://discord.com/channels/996791218879086662/1002130113565053008/1037771910806765598).

**Comment by alexfrancoeur** [comment]
@richardgill I know you're in the CLI right now, is this something easy enough to fix?

**Comment by kostasb** [comment]
This works well with the latest CLI.
