### ISSUE TITLE
Check for existing version on package manager install

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#773]
**Is your feature request related to a problem? Please describe.**

If I try to run `xata init` on a non npm env (yarn or pnpm), the process try to install `@xata.io/client` with npm and my entire dependencies are broken.

**Describe the solution you'd like**

I would like to at least be able to skip the client install step, also, if the client is already installed, let’s skip this step.

**Comment by SferaDev** [comment]
Duplicated, and fixed in version coming out today!

**Comment by fabien0102** [comment]
This is why I didn’t find the issue in the open issue board! Looking forward for this version 😁

**Comment by SferaDev** [comment]
@fabien0102 You can try it in the canary tag, I have not been able to in depth test it

> npx @xata.io/cli@0.0.0-alpha.ve23b0f2

**Comment by SferaDev** [comment]
Relevant code and logic: https://github.com/xataio/client-ts/commit/03e30fc48bff131d4b1d8fdafc3b664bf7c8ded3#diff-ceb21cc5f73500c4e7f57bade167f4f8bd60a765f87a551636c10b19de33a86fR187-R230

**Comment by fabien0102** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1761469/202232069-9e8ad50d-d7d7-45e8-ad2e-57deb962687f.png">

Sweeeeeeet, just a little nitpick feedback, why are we installing the client if it’s already installed? 🤔 (this might cause some version problems)

**Comment by SferaDev** [comment]
Let me re-open this issue and follow-up with checking the installed version + asking to update or keep the existing one

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/203044761-67c35956-83ca-4710-8eaa-b6649e9a55aa.png)

Example from astro starter for checking/asking to install deps with the correct package manager.

**Comment by richardgill** [comment]
@SferaDev I feel like I've fixed this now
