### ISSUE TITLE
Allow sorting by column and desc object

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#791]
<img width="917" alt="Screenshot 2022-11-27 at 11 42 11" src="https://user-images.githubusercontent.com/2181866/204131029-c7c6cf2a-e301-4053-919d-4162c901a645.png">

**Comment by alexfrancoeur** [comment]
@SferaDev is this still valid?

**Comment by philkra** [comment]
It is possible to sort on `xata.createdAt` which is technically an object and the `object` type will be sunset in December 2023. Closing the issue
