### ISSUE TITLE
Add column is showing `[object Object]` instead of the column name

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#801]
**Describe the bug**

<img width="322" alt="image" src="https://user-images.githubusercontent.com/1761469/204844354-545b12dd-0bed-42dc-b0a9-439580cfde58.png">

**To Reproduce**

```bash
$ npx degit xataio/examples/apps/starter-sveltekit#sveltekit-starter sveltekit-starter-test
$ cd sveltekit-starter-test
$ pnpm install
$ pnpm xata:init
$ pnpm dev
```

**Expected behavior**

I should see `title`, `description` and `url` instead of `[object Object]`

**Comment by SferaDev** [comment]
@gimenete You're touching those files in your current PR I believe, can you take a look?
