### ISSUE TITLE
Support vitejs/solidstart

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#802]
**Is your feature request related to a problem? Please describe.**

In a ViteJS env, I need to:

1. prefix the .env key with `VITE_`
2. Add the following file to set the correct key to the SDK
```ts
import { XataClient } from './xata.codegen.server';

export const xata = new XataClient({
	apiKey: import.meta.env.VITE_XATA_API_KEY
});
```

**Describe the solution you'd like**

I would like to not have to do this if possible

**Additional context**

[
](https://vitejs.dev/guide/env-and-mode.html#env-variables)

**Comment by SferaDev** [comment]
Is this pure Vite or that solidstart framework? I don't think in pure Vite SSR/SSG you really need it, and if it's happening for solidstart then it's a bug of their own. Doing this kind of prefixes is a bad smell, and could eventually lead to helping unexperienced to leak their credentials in client bundles.

**Comment by SferaDev** [comment]
Related: https://github.com/solidjs/solid-start/issues/480
