### ISSUE TITLE
Strictly require not null column value

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#813]
**Feature request**:
Add an option for strictly required column values so that the SDK will reject creating a record if it does not hold a value for the specified column/s.

**Description**:
The Xata API does not provide a "Not null" constraint without a default value (see open [feature request](https://feedback.xata.io/feature-requests/p/strict-not-null-constraint)) which, for technical reasons, may not be available shortly.
Currently, to strictly require a column value, SDK calls would need to be wrapped in functions that require values. Implementing this feature would help simplify user code.

**Comment by SferaDev** [comment]
Makes sense when we have not null without default value. Until then, not worthy. The code is quite easy to add support for both scenarios.

**Comment by kostasb** [comment]
As discussed, in order to maintain clean feature parity across the REST API and SDK, the way to move forward here will be to pursue a "strict not null without defaults" constraint at the API level.
