### ISSUE TITLE
ambiguous indirect export: buildClient xata.ts:2:9

### ISSUE THREAD

**Issue by Exrun94** [xataio/client-ts#823]
Hello there!
It's my first time I wanted to try Xata and I have followed the instructions using the CLI to generate the xata.ts and I've been getting this error

`Uncaught SyntaxError: ambiguous indirect export: buildClient [xata.ts:2:9](http://localhost:5173/src/xata.ts?t=1671370867641)`

[Repo](https://github.com/Exrun94/code-perfect-react-boilerplate/tree/development) to reproduce the issue 

The repo is a boilerplate code I am creating for myself using Vite + React & Typescript

**Comment by SferaDev** [comment]
Hey @Exrun94 thanks for your report. I will investigate the error further tomorrow morning!

In any case, some early thoughts that can help us find a solution. I suspect it's related to `plugin-react-swc`, to check if my gut is right could you:

- Update the plugin to v3.0.1 and check if the error is gone? (They have a couple of points in the change log that are interesting)
- Run the build command and check if the error pops in production? (swc is not used in build only in development server)
- Change to the normal, battle-tested old plugin that does not use swc? (We have some samples with vite and we never surfaced this issue)

In any case, I'll try debug it and open an issue if needed to their repo as a library author.

**Comment by Exrun94** [comment]
Thanks for the quick reply, I will give these suggestions a try and let you know

**Comment by Exrun94** [comment]
Good call, I confirm upgrading `plugin-react-swc` to v3.0.1 has fixed the problem there! 

And thank you for pointing out the security issues of exposing the API keys,  I am aware of it already and thinking of what I want to do, honestly probably just go with NextJS, I haven't used serverless functions before nor SSR plugins but I will see how much of a overhead is to set these up are and decide what I want to do. 
Cheers

**Comment by SferaDev** [comment]
Could you reach out via support@xata.io so @kostasb can make the arrangements to flag you in the Xata Workers beta?

**Comment by Exrun94** [comment]
Thank you, I've sent them an email! :)
