### ISSUE TITLE
Request of a dependency is an expression

### ISSUE THREAD

**Issue by atilafassina** [xataio/client-ts#829]
**Describe the bug**

When using the Xata client the console is polluted with warnings about the client requiring a dependency via an expression.

```
warn  - ../@xata.io+client@0.21.5_typescript@4.9.4/node_modules/@xata.io/client/dist/index.mjs
Critical dependency: the request of a dependency is an expression
```

**To Reproduce**

Use Xata Client with Next.js for example (or another project running Webpack, I'd assume)

**Expected behavior**

No warnings.

**Software version**

- Next.js 13.0.7
- `@xata.io/client` 0.21.5

**Comment by SferaDev** [comment]
Probably related to having a require in git branch resolution. Will hide it a bit more to see if we can make webpack happy.

**Comment by SferaDev** [comment]
Have tried multiple potential fixes and none worked...

**Comment by SferaDev** [comment]
I think I can remove this warning in the next version 🤞🏻

**Comment by mattapperson** [comment]
So the issue here is `const { execSync } = await import(nodeModule);` as next is transpiring this module and does not support dynamic import statements where the import name is not statically checkable
