### ISSUE TITLE
Add region to xata init --help examples

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#831]
**Describe the bug**
The examples in `xata init --help` are missing the (now necessary) region part in the url

> EXAMPLES
  Initialize a new project
  $ xata init --db https://workspace-1234.xata.sh/db/database-name
  Initialize a new project using a schema dump
  $ xata init --db https://workspace-1234.xata.sh/db/database-name --schema schema.json
  Initialize a new project without flags. The workspace and database will be asked interactively
  $ xata init

Also the FLAGS section mentions: `--db=https://{workspace}.xata.sh/db/{database}`

maybe add the region part as:
`https://workspace-1234.region.xata.sh/db/database-name`

**Comment by SferaDev** [comment]
@kostasb Do you feel fancy to open up a PR? 😄
