### ISSUE TITLE
Investigate type recursion performance

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#851]
**Describe the bug**
Schema recursion created by table link loops has a performance impact beyond 2-3 levels of recursion, also depending on the number of tables.

Example repro schema: [recursion_repro_schema.txt](https://github.com/xataio/client-ts/files/10392839/recursion_repro_schema.txt)

Investigate performance improvements to achieve multiple levels of recursion (possibly a max of 5).

**Comment by alexfrancoeur** [comment]
This actually feels like it could be a P1 or P2 since it's impacting performance. What do you think @exekias @philkra ?

**Comment by philkra** [comment]
The performance penalty is "only" experienced with IDE autocomplete.

**Comment by kostasb** [comment]
As of client v0.24.0 recursion is limited to 2 nested levels which prevents such performance issues from surfacing.
