### ISSUE TITLE
[xata schema edit] Wrong `defaultValue` on `string` when not defined

### ISSUE THREAD

**Issue by fabien0102** [xataio/client-ts#863]
**Describe the bug**

Using `xata edit schema`, when I’m creating a `string` column without providing any `defaultValue`, the value is set as `"undefined"` instead of an empty string (default value in the UI)

**Comment by kostasb** [comment]
This causes creating unique columns with `xata schema edit` to fail (`Error: Internal Error (RequestID: 78447486-c8fa-9b38-8aab-5563ba5d479e)`) because it tries to add defaultValue and uniqueness on the column.

**Comment by SferaDev** [comment]
@fabien0102 and @kostasb Can you give it a try with the next experimental version and see if it's fixed for you?

> npx @xata.io/cli@0.0.0-alpha.vd99266f

**Comment by kostasb** [comment]
> @fabien0102 and @kostasb Can you give it a try with the next experimental version and see if it's fixed for you?
> 
> > npx @xata.io/[cli@0.0.0-alpha.vd99266f](mailto:cli@0.0.0-alpha.vd99266f)

Worked well for me. The CLI requires a Default value when Not null is enabled and I was also able to create a `unique` string column. Thanks!

**Comment by kostasb** [comment]
A followup/implication issue: https://github.com/xataio/client-ts/issues/871
