### ISSUE TITLE
[xata schema edit] CLI should not allow enabling unique and not null

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#871]
**Describe the bug**

Setting both unique and notnull to true is currently allowed by the CLI

![image](https://user-images.githubusercontent.com/15780449/214511539-ec4f8645-b5ed-4517-947f-042b4b33d69c.png)

but the `run migration` step fails with an `Internal Error` which may be inexplicable to the end user.

Enabling unique or not null should make the other unavailable (due to defaultValue)

**Comment by SferaDev** [comment]
@richardgill Do you think it's feasible to get this also sorted out?

**Comment by kostasb** [comment]
This is fixed, setting unique + notnull raises `❯ Invalid unique: Column cannot be both `unique: true` and `notNull: true``
