### ISSUE TITLE
SDK shouldn't suggest the link id in search filters

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#896]
**Describe the bug**
Filters in search do not support using any of the linked record columns, including `id`

[Search docs](https://xata.io/docs/typescript-client/search) mention:
> for links records you can filter by the ID of the linked record, but not any of the other columns. 

The sdk autocomplete suggests the `.id` for links:
![image](https://user-images.githubusercontent.com/15780449/218128462-12a99ab7-d8df-40e9-9f91-e9c7e0a623d2.png)
while links in such filters are called just by the link column (`"linked_workspace":"value"` in the above case).

We should consider removing the id field from suggestions in the context of search filters.

**Comment by alexfrancoeur** [comment]
+1 on this, what do you think @SferaDev ?

**Comment by SferaDev** [comment]
It's actually a bug on the backend where internal columns are not indexed (I'd, version, createdAt, etc...). @andrew-farries is taking a look I believe

**Comment by philkra** [comment]
Is this issue this present?

**Comment by kostasb** [comment]
This issue has been resolved, filters by link.id work:

```const records = await xata.search.all("sdk", {
  tables: [
    {
      table: "databases",
      filter: {
        "linked_workspace.id": "19v8n2",
      },
    },
  ],
});
```

Documentation adjustments are not required either any more.
