### ISSUE TITLE
xata random-data errors with unique columns

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#913]
**Describe the bug**
In the presence of a column with uniqueness enabled, xata random-data will eventually fail due to generating a duplicate value.

```
xata schema dump

{
  "tables": [
    {
      "name": "test",
      "columns": [
        {
          "name": "uniquestring",
          "type": "string",
          "unique": true
        }
      ]
    }
  ]
}

```

Error output:

> xata random-data --records 1000
    Error: Bulk operation failed

**Comment by SferaDev** [comment]
Duplicated #684
