### ISSUE TITLE
Xata schema edit should allow "not null" on multiple type

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#916]
The documentation states the multiple type supports the notNull constraint: https://xata.io/docs/concepts/data-model#multiple

>  The multiple type represents an array of strings. Set notNull to require a value.

`xata schema edit` does not support it

![image](https://user-images.githubusercontent.com/15780449/220673184-f9ae15ee-2d0e-4712-adde-302196b56ef3.png)

**Comment by kostasb** [comment]
Depends on https://github.com/xataio/xata/issues/1942

**Comment by eemmiillyy** [comment]
This is possible now for pgroll branches with this PR https://github.com/xataio/client-ts/pull/1430.

**Comment by philkra** [comment]
closing as done via https://github.com/xataio/client-ts/pull/1430
