### ISSUE TITLE
Split XataRecord from Entity in codegen

### ISSUE THREAD

**Issue by SferaDev** [xataio/client-ts#92]
Right now:

```ts
export interface Foo extends XataRecord {
  property: string | null;
}
```

Improves DX:

```ts
export interface Foo {
  id: string;
  property: string | null;
}

export type FooRecord = Foo & XataRecord;
```

**Comment by gimenete** [comment]
Why do you think splitting entities and records improves the DX?

**Comment by SferaDev** [comment]
> Why do you think splitting entities and records improves the DX? Could you ellaborate on that?

I was working with xata on a side project, and when typing functions that received or returned the entities (without caring of the internal Record properties) was not easy. I was able to do ``Omit<Team, keyof XataRecord>`` but it wasn't idiomatic.

Let's say I have a function that creates many teams.

```ts
async function initTeams(teams: Team[]): Promise<TeamRecord[]>;
```

Without that differentiation you don't have an easy way to get the entity type (which you will probably pass around between functions).

**Comment by gimenete** [comment]
I see. That makes sense 👍 Thanks for the explanation!
