### ISSUE TITLE
xata init --force should clear migration files

### ISSUE THREAD

**Issue by kostasb** [xataio/client-ts#992]
**Describe the bug**
When running `xata init --force` the command should take care of cleaning up, or archiving in some way so they don't get in the way, any existing migration files.

Use case: changing the database associated with a project by initializing with a new db. Currently, the user needs to zero off the .xata/migrations directory otherwise the projects ends up in a conflicting state.

**To Reproduce**

The following script is with `@xata.io/cli/0.11.19`

```
//in a project with a db configured already, having migration files
my-xata-app % ls .xata/migrations 
mig_ch4j00rfqdrklh9k3t1g_a5ebae2a.json	mig_ch4j00rfqdrklh9k3t2g_87ff5a35.json

my-xata-app % xata init --force
...configure a new db

my-xata-app % xata pull main
There are new migrations on both the local and remote branches. Please run `xata rebase` to resolve the conflicts.

my-xata-app % xata rebase main
    Error: ENOENT: no such file or directory, open '/Users/kostas/Documents/pworkflow/my-xata-app/.xata/migrations/mig_cgvs0dr8ecc81uop9jb0_65112536.json'
    Code: ENOENT
```

**Comment by SferaDev** [comment]
@kostasb https://github.com/xataio/client-ts/pull/1092 Can you check different scenarios with this change? I will also test it out when I get a chance.
